# 📚 Section 1: Introduction to NumPy
> NumPy 소개 — What NumPy is, and why it replaces Python lists for numerical/data work

---
# 🎯 Learning Objective
Today I want to learn:
- [x] What NumPy is, what `ndarray` is, and why it exists
- [x] How NumPy's `ndarray` differs from a Python `list` (types, memory, speed)
- [x] How to import NumPy correctly and create/inspect a basic array

---
# 🧠 Concept

## What is it?
*(Explain it in your own words.)*

NumPy (**Num**erical **Py**thon) is Python's core library for numerical computing. Its central data structure is the `ndarray` (n-dimensional array) — a container built for a single, uniform data type and backed by a C-level engine, which is exactly what makes it so much faster than plain Python for large-scale math.

NumPy(Numerical Python)는 파이썬에서 수치 계산을 위한 핵심 라이브러리입니다. 핵심 자료구조는 `ndarray`(n차원 배열)로, 하나의 통일된 데이터 타입만 담는 컨테이너이며 C 언어 기반 연산 엔진을 내장하고 있어 대규모 수치 계산에서 순수 파이썬보다 훨씬 빠른 속도를 보여줍니다.

### `list` vs `ndarray` at a glance / 한눈에 보는 비교

| Aspect / 비교 항목 | Python `list` | NumPy `ndarray` |
|---|---|---|
| Element types / 요소 타입 | Mixed types allowed (다양한 타입 혼합 가능) | Same type only (동일 타입만 허용) |
| Memory layout / 메모리 구조 | Scattered pointers (분산된 포인터) | One contiguous block (연속된 메모리 블록) |
| Math speed / 연산 속도 | Slow — needs a loop (느림 — 반복문 필요) | Fast — vectorized, C-level (빠름 — 벡터화 연산) |
| `+` operator / `+` 연산자 | Concatenation (리스트 연결) | Element-wise addition (요소별 덧셈) |
| Typical use / 주요 용도 | General-purpose container (범용 컨테이너) | Numeric computation (수치 연산 전용) |

## Why do we use it?
*(When is it useful?)*

Because it's fast and expressive: an operation that would need an explicit `for` loop in plain Python can be written as one vectorized expression, and that expression runs at C speed instead of interpreted-Python speed. The difference becomes enormous once your data passes a few thousand rows.

빠르고 표현력이 좋기 때문입니다. 순수 파이썬이었다면 `for` 문이 필요했을 연산을 한 줄짜리 벡터화된 표현식으로 작성할 수 있고, 이 표현식은 인터프리터 속도가 아닌 C 수준의 속도로 실행됩니다. 데이터가 수천 행을 넘어서는 순간부터 이 차이는 매우 커집니다.

## When is it used in Business Analytics?
*(Real-world use case)*

- Pandas' `DataFrame` stores its underlying data as NumPy arrays, so every Pandas operation is quietly powered by NumPy underneath.  
Pandas의 `DataFrame`은 내부 데이터를 NumPy 배열로 저장하므로, 모든 Pandas 연산은 실제로는 내부적으로 NumPy가 처리합니다.
- Summing or averaging tens of millions of sales/customer rows without writing a loop.  
수천만 행의 매출·고객 데이터를 반복문 없이 합계·평균 계산할 때.
- Preprocessing (normalizing, transforming) data before feeding it into a machine learning model.  
머신러닝 모델에 데이터를 넣기 전 정규화·변환 등 전처리 작업을 할 때.
- Calculating statistical metrics — mean, standard deviation, percentiles — for a KPI report.  
KPI 리포트를 위한 평균, 표준편차, 분위수 등 통계 지표를 계산할 때.

---
# 📝 Syntax

## Basic Syntax

In [1]:
# Install once from the terminal (not run here):
# pip install numpy

# Standard import convention — always alias as np
import numpy as np

# Check the installed version
print(np.__version__)

# Create a basic ndarray from a Python list
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

2.4.4
[1 2 3 4 5]
<class 'numpy.ndarray'>


## Common Variations

In [2]:
# Importing without the alias still works, but forces the verbose full name everywhere
import numpy
print(numpy.array([1, 2, 3]))

# ndarray can be built from other iterables too, not just lists
from_list = np.array([1, 2, 3])
from_tuple = np.array((1, 2, 3))
print(from_list, from_tuple)

# NumPy infers ONE shared dtype for the whole array
print(np.array([1, 2, 3]).dtype)          # all integers -> an int dtype
print(np.array([1.0, 2, 3]).dtype)        # one float forces the rest to float
print(np.array([1, "2", 3]).dtype)        # one string forces EVERYTHING to string!

[1 2 3]
[1 2 3] [1 2 3]
int64
float64
<U21


---
# 🧪 Small Examples

## Example 1: What NumPy Buys You — Speed at Scale
### 1-1. NumPy란? (What is NumPy?)

In [3]:
import numpy as np
import time

# Simulate 1 million sales records
sales_data = np.random.randint(1000, 100000, size=1_000_000)

# NumPy way — sum the whole array at once
start = time.time()
total_numpy = np.sum(sales_data)
numpy_time = time.time() - start

# Plain Python loop way
start = time.time()
total_loop = sum([x for x in sales_data])
loop_time = time.time() - start

print(f"NumPy time: {numpy_time:.4f}s")
print(f"Python loop time: {loop_time:.4f}s")
print(f"NumPy is about {loop_time / numpy_time:.0f}x faster")

NumPy time: 0.0004s
Python loop time: 0.0891s
NumPy is about 236x faster


## Example 2: `list` vs `ndarray` in Practice
### 1-2. Python list vs NumPy ndarray 비교

In [4]:
import numpy as np

# Python list
py_list = [1, 2, 3, 4, 5]
print(type(py_list))

# NumPy ndarray
np_array = np.array([1, 2, 3, 4, 5])
print(type(np_array))

# Mixed types: list keeps them as-is, ndarray upcasts everything to one type
mixed_list = [1, "hello", True, 3.14]
print(mixed_list)

mixed_array = np.array([1, "hello", True, 3.14])
print(mixed_array)
print(mixed_array.dtype)

# The same operator, two different behaviors
print([x * 2 for x in py_list])   # list needs a loop/comprehension
print(np_array * 2)               # ndarray: one vectorized line

<class 'list'>
<class 'numpy.ndarray'>
[1, 'hello', True, 3.14]
['1' 'hello' 'True' '3.14']
<U32
[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


## Example 3: Practice — Import NumPy & Check the Version
### 연습 문제 (Practice Problem)

**Task / 과제:** Import NumPy using its standard alias, then print the installed version.
NumPy를 표준 별칭으로 import한 뒤, 설치된 버전을 출력하세요.

Fill in both blanks marked `________` below, then run the cell.
아래 두 개의 빈칸(`________`)을 채운 후 셀을 실행하세요.

In [7]:
# ✏️ Practice — replace each ________ line below, then run this cell.
# ✏️ 연습 문제 — 아래 각 ________ 줄을 채운 후 셀을 실행하세요.

# TODO 1: import NumPy using its standard alias
import numpy as np

# TODO 2: print the installed NumPy version
print(np.__version__)

print("✅ If both lines above are correct, re-run this cell to see the version number.")
print("✅ 위 두 줄이 올바르면, 셀을 다시 실행했을 때 버전 번호가 나타납니다.")

2.4.4
✅ If both lines above are correct, re-run this cell to see the version number.
✅ 위 두 줄이 올바르면, 셀을 다시 실행했을 때 버전 번호가 나타납니다.


---
# ⚠️ Common Mistakes

**Mistake 1 — Forgetting the `as np` alias.**
Writing `import numpy` alone forces you to type the verbose full name — `numpy.array()` — everywhere in your code from then on.  
`import numpy`만 쓰고 `as np`를 생략하면, 이후 코드 전체에서 `numpy.array()`처럼 풀네임을 계속 써야 해서 번거롭습니다.  
✅ **Fix:**  Always write `import numpy as np`. It's the universal convention — every tutorial, library, and teammate expects it.  
✅ **해결법:** 항상 `import numpy as np`로 작성하세요. 모든 튜토리얼, 라이브러리, 동료가 이 관례를 기대합니다.

**Mistake 2 — Using a non-standard alias.**
Aliasing NumPy as something other than `np` (e.g. `import numpy as nmp`) technically works, but it breaks the shared convention and confuses teammates reading your code.  
`np`가 아닌 다른 별칭(예: `import numpy as nmp`)을 사용해도 기술적으로는 작동하지만, 공통 관례를 깨뜨려 동료들이 코드를 읽을 때 혼란을 줍니다.  
✅ **Fix:** Stick to `np` — no exceptions, even in solo projects.  
✅ **해결법:** 혼자 하는 프로젝트라도 예외 없이 `np`를 사용하세요.

**Mistake 3 — Assuming `np.array()` keeps mixed types.**
`np.array([1, "2", 3])` silently converts every element to the *same* type (usually string) instead of raising an error — so later math on that array will fail or behave unexpectedly.  
`np.array([1, "2", 3])`처럼 타입을 섞으면 에러 없이 모든 요소가 동일한 타입(보통 문자열)으로 자동 변환됩니다 — 이후 이 배열에 수치 연산을 하면 실패하거나 예상과 다르게 동작합니다.  
✅ **Fix:** Check `.dtype` right after creating an array from mixed-looking data, before you do any math on it.  
✅ **해결법:** 타입이 섞였을 가능성이 있는 데이터로 배열을 만들었다면, 연산을 하기 전에 `.dtype`을 먼저 확인하세요.

**Mistake 4 — Confusing `+` on `list` vs `ndarray`.**
`[1, 2] + [3, 4]` concatenates into `[1, 2, 3, 4]`, but `np.array([1, 2]) + np.array([3, 4])` adds element-wise into `[4, 6]` — the same symbol means two completely different operations.  
`[1, 2] + [3, 4]`는 `[1, 2, 3, 4]`로 이어붙이기가 되지만, `np.array([1, 2]) + np.array([3, 4])`는 요소별 덧셈으로 `[4, 6]`이 됩니다 — 같은 기호가 완전히 다른 연산을 의미합니다.  
✅ **Fix:** Before writing `+`, know which type you're holding — `type(x)` or `.dtype` will tell you.  
✅ **해결법:** `+`를 쓰기 전에 지금 다루는 게 어떤 타입인지 먼저 확인하세요 — `type(x)`나 `.dtype`으로 확인할 수 있습니다.

---
# 💡 Tips
Useful tips or shortcuts

- Run `np.__version__` right after importing in a new environment — it's the fastest way to confirm the install worked.  
새 환경에서 import 직후 `np.__version__`을 실행해 보세요 — 설치가 잘 됐는지 가장 빠르게 확인하는 방법입니다.
- `type(x)` tells you `list` vs `ndarray`; `x.dtype` tells you what's *inside* the ndarray. Get in the habit of checking both when something behaves unexpectedly.  
`type(x)`는 `list`인지 `ndarray`인지 알려주고, `x.dtype`은 ndarray *내부* 타입을 알려줍니다. 예상과 다르게 동작할 때는 둘 다 확인하는 습관을 들이세요.
- If you only remember one reason to switch from `list` to `ndarray`, make it this: any time you catch yourself writing a `for` loop over numbers, there's probably a one-line NumPy way to do it.  
이유를 하나만 기억해야 한다면 이것으로 하세요: 숫자에 대해 `for` 문을 쓰고 있다면, 대부분 NumPy로 한 줄에 처리할 수 있습니다.

---
# 🔗 Related Concepts

```
Python (lists, loops, functions)
        ↓
🔵 Section 1 — NumPy Introduction   ← you are here
   (ndarray concept, list vs ndarray)
        ↓
Section 2 — ndarray Creation
   (np.array, zeros, ones, arange, linspace, eye)
        ↓
Sections 3-9 — attributes, indexing, manipulation,
   vectorization, aggregation, random/sorting
        ↓
Section 10 — Pandas + NumPy integration
        ↓
Sections 11-12 — Business KPIs, missing values
        ↓
Pandas → SQL → Tableau
```

*How is today's topic connected to other concepts?*

This section is the foundation for everything else in this NumPy series: `ndarray` is the object every later section operates on (creating it, indexing it, reshaping it, aggregating it). It's also the foundation for Pandas — a Pandas `DataFrame` is, underneath, a collection of NumPy arrays, so understanding `ndarray` now makes the Pandas guide much easier later.

이번 섹션은 앞으로 이어질 모든 NumPy 내용의 기초입니다: `ndarray`는 이후 모든 섹션이 다루는 대상(생성, 인덱싱, reshape, 집계 등)입니다. 또한 Pandas의 기초이기도 합니다 — Pandas의 `DataFrame`은 내부적으로 NumPy 배열의 집합이므로, 지금 `ndarray`를 이해해두면 나중에 Pandas 가이드를 훨씬 쉽게 배울 수 있습니다.

---
# 💼 Business Example
*How would a Business Analyst use this?*

**Scenario / 시나리오:**
You're a data analyst at an e-commerce company. Leadership wants to know (1) why the daily sales report job should be rewritten with NumPy instead of plain Python loops, and (2) which customers currently qualify as VIPs by monthly spend.
당신은 이커머스 회사의 데이터 분석가입니다. 경영진은 (1) 일별 매출 리포트 작업을 순수 파이썬 반복문 대신 NumPy로 다시 짜야 하는 이유와, (2) 월 구매금액 기준으로 현재 VIP 고객이 누구인지 알고 싶어합니다.

**To-do / 할 일:**
- [x] Generate/simulate a large sales dataset and time both a loop-based and a NumPy-based sum.  
대용량 매출 데이터를 생성하고, 반복문 방식과 NumPy 방식의 합계 계산 시간을 비교합니다.
- [x] Build a small array of customer purchase amounts.  
고객 구매금액으로 작은 배열을 만듭니다.
- [x] Apply 10% VAT to every purchase in one line.  
한 줄로 모든 구매금액에 부가세 10%를 적용합니다.
- [x] Flag customers spending ≥ 300,000 as VIP.  
300,000원 이상 지출한 고객을 VIP로 표시합니다.

In [6]:
import numpy as np
import time

# --- Part 1: Why NumPy for the daily sales report? ---
sales_data = np.random.randint(1000, 100000, size=1_000_000)

start = time.time()
total_numpy = np.sum(sales_data)
numpy_time = time.time() - start

start = time.time()
total_loop = sum([x for x in sales_data])
loop_time = time.time() - start

print(f"NumPy: {numpy_time:.4f}s   |   Python loop: {loop_time:.4f}s")
print(f"NumPy is about {loop_time / numpy_time:.0f}x faster on 1M rows")

# --- Part 2: Flag VIP customers ---
purchases = np.array([150000, 320000, 80000, 450000, 210000])

purchases_with_tax = purchases * 1.1
print("With 10% VAT:", purchases_with_tax)

is_vip = purchases >= 300000
print("VIP flags:", is_vip)
print("VIP purchase amounts:", purchases[is_vip])

NumPy: 0.0004s   |   Python loop: 0.0753s
NumPy is about 209x faster on 1M rows
With 10% VAT: [165000. 352000.  88000. 495000. 231000.]
VIP flags: [False  True False  True False]
VIP purchase amounts: [320000 450000]


---
# 📝 Summary
*Write today's concept in 3~5 sentences.*

NumPy is Python's core library for numerical computing, built around the `ndarray` — a single-type, contiguous array that runs at C speed. Unlike a Python `list`, which can mix types but pays for that flexibility with loop-based, interpreted-speed math, `ndarray` trades flexibility for speed and lets you write whole-array operations (like `arr * 2` or `arr >= 300000`) as one line instead of a loop. This matters in practice because Pandas is built on top of NumPy arrays, and any BA/DA task involving large datasets — summing millions of rows, computing KPIs, preprocessing for ML — leans on this speed. The most common beginner trip-up is the import alias and silent type upcasting, both easy to avoid once you know to watch for them.

NumPy는 파이썬의 핵심 수치 계산 라이브러리로, 단일 타입의 연속된 메모리 구조를 가지며 C 수준 속도로 동작하는 `ndarray`를 중심으로 합니다. 다양한 타입을 섞을 수 있지만 그 대가로 반복문 기반의 느린 연산을 감수해야 하는 파이썬 `list`와 달리, `ndarray`는 유연성을 속도와 맞바꿔서 `arr * 2`나 `arr >= 300000` 같은 배열 전체 연산을 반복문 없이 한 줄로 작성할 수 있게 해줍니다. 이는 실무에서 매우 중요한데, Pandas 자체가 NumPy 배열 위에 구축되어 있고, 수백만 행 합산·KPI 계산·머신러닝 전처리처럼 대용량 데이터를 다루는 모든 BA/DA 업무가 이 속도에 의존하기 때문입니다. 초보자가 가장 흔히 걸려 넘어지는 부분은 import 별칭과 조용한 타입 자동 변환이며, 둘 다 미리 알고 있으면 쉽게 피할 수 있습니다.

---
# 📌 One Sentence Summary
Today's topic in ONE sentence.

> NumPy replaces Python lists with a single-type `ndarray` that runs numeric operations at C speed instead of looping in pure Python.

> NumPy는 파이썬 리스트 대신, 순수 파이썬 반복문이 아닌 C 수준 속도로 수치 연산을 수행하는 단일 타입 `ndarray`를 제공합니다.

---
# ❓ Review Questions

**Q1.** What is the one core data structure that NumPy is built around, and what does "n-dimensional" mean in its name?
NumPy가 중심으로 삼는 핵심 자료구조는 무엇이며, 이름의 "n차원(n-dimensional)"은 무슨 뜻인가요?

**Q2.** Name two concrete differences between a Python `list` and a NumPy `ndarray`.
Python `list`와 NumPy `ndarray`의 구체적인 차이점을 두 가지 말해보세요.

**Q3.** What happens to the dtype of `np.array([1, "2", 3.0])`, and why does that matter before doing math on it?
`np.array([1, "2", 3.0])`의 dtype은 어떻게 되며, 이 배열로 연산을 하기 전에 왜 이 점이 중요한가요?

**Q4.** What is the standard import convention for NumPy, and what's the risk of not following it?
NumPy의 표준 import 관례는 무엇이며, 이를 따르지 않으면 어떤 위험이 있나요?

**Q5.** Why does understanding NumPy's `ndarray` make it easier to learn Pandas later?
NumPy의 `ndarray`를 이해하는 것이 나중에 Pandas를 배울 때 왜 도움이 되나요?

---
*📅 Try answering these again in a few days.*