# 📚 Section 2: Creating ndarrays
> ndarray 생성 — Six core functions for building arrays from scratch: `array`, `zeros`/`ones`, `arange`, `linspace`, `full`, `eye`

---
# 🎯 Learning Objective
Today I want to learn:
- [x] The six core ways to create a NumPy array: `array`, `zeros`/`ones`, `arange`, `linspace`, `full`, `eye`
- [x] The key difference between `arange` (step-based, stop excluded) and `linspace` (count-based, stop included)
- [x] How to control `dtype` and `shape` when creating arrays, and the common pitfalls around both

---
# 🧠 Concept

## What is it?
*(Explain it in your own words.)*

NumPy gives you several dedicated functions for building an `ndarray` from scratch, rather than always typing out every value by hand. Each function targets a different starting point — some build from data you already have, others build a blank canvas of a given shape or size.

NumPy는 모든 값을 직접 입력하지 않아도 `ndarray`를 처음부터 만들 수 있는 여러 전용 함수를 제공합니다. 각 함수는 서로 다른 출발점을 가정합니다 — 이미 가진 데이터로 만드는 함수도 있고, 특정 모양이나 크기의 빈 배열을 만드는 함수도 있습니다.

### Which function, when? / 언제 어떤 함수를?

| Function / 함수 | Use when... / 언제 사용? | Key parameter / 핵심 파라미터 |
|---|---|---|
| `np.array()` | You already have the data, e.g. a list (이미 데이터(리스트)가 있을 때) | `data` |
| `np.zeros()` / `np.ones()` | You need a blank baseline array to fill in later (나중에 채울 빈 배열이 필요할 때) | `shape` |
| `np.arange()` | You know the step size (간격(step)을 알고 있을 때) | `start, stop, step` |
| `np.linspace()` | You know how many points you want (몇 개의 점이 필요한지 알고 있을 때) | `start, stop, num` |
| `np.full()` | Every element should start at one specific value (모든 원소가 같은 값으로 시작해야 할 때) | `shape, fill_value` |
| `np.eye()` | You need an identity matrix (단위 행렬이 필요할 때) | `N` |

## Why do we use it?
*(When is it useful?)*

Because picking the right creation function saves you from writing manual loops or hardcoding values — `np.arange(1, 366)` gives you a full year of day numbers in one call, and `np.zeros(12)` gives you a ready-to-fill 12-month tracker without typing twelve zeros by hand.

알맞은 생성 함수를 고르면 반복문을 직접 작성하거나 값을 일일이 하드코딩할 필요가 없어지기 때문입니다. `np.arange(1, 366)` 한 줄이면 1년치 일수를 만들 수 있고, `np.zeros(12)` 한 줄이면 0을 열두 번 직접 입력하지 않고도 채울 준비가 된 12개월 트래커를 만들 수 있습니다.

## When is it used in Business Analytics?
*(Real-world use case)*

- Building a blank 12-month or 365-day tracker before real data arrives.  
실제 데이터가 들어오기 전에 12개월/365일짜리 빈 트래커를 만들 때.
- Generating price, age, or score bins for a histogram or segmentation.  
히스토그램이나 세그멘테이션을 위한 가격·나이·점수 구간(bin)을 만들 때.
- Setting up evenly spaced thresholds for A/B test variants or discount-rate scenarios.  
A/B 테스트 variant나 할인율 시나리오를 위한 균등 간격 임계값을 설정할 때.
- Initializing a missing-value placeholder array before filling in what you actually have.  
실제 데이터를 채우기 전에 결측치 placeholder 배열을 초기화할 때.

---
# 📝 Syntax

## Basic Syntax

In [1]:
import numpy as np

# np.array() — from a Python list (or list of lists)
print(np.array([1, 2, 3]))

# np.zeros() / np.ones() — filled with 0s / 1s
print(np.zeros(5))
print(np.ones((2, 3)))

# np.arange(start, stop, step) — stop is EXCLUDED
print(np.arange(0, 10, 2))

# np.linspace(start, stop, num) — stop is INCLUDED, you specify the COUNT
print(np.linspace(0, 1, 5))

# np.full(shape, fill_value) — filled with one specific value
print(np.full((3, 4), 7))

# np.eye(N) — N x N identity matrix
print(np.eye(3))

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Common Variations

In [2]:
import numpy as np

# dtype control — force a specific type on creation
print(np.array([1, 2, 3], dtype=float))
print(np.zeros((2, 2), dtype=int))
print(np.eye(3, dtype=int))

# shape must be a TUPLE for zeros/ones/full — two bare args will not work
print(np.zeros((3, 4)).shape)   # correct: one tuple argument

# arange (step-based) vs linspace (count-based) side by side
print(np.arange(0, 1, 0.25))            # step of 0.25 -> floating point risk
print(np.linspace(0, 1, 5))             # 5 points -> always exact endpoints

# linspace can exclude the endpoint too
print(np.linspace(0, 1, 5, endpoint=False))

# full() with np.nan is a common missing-value placeholder (float arrays only)
print(np.full(4, np.nan))

[1. 2. 3.]
[[0 0]
 [0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 4)
[0.   0.25 0.5  0.75]
[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]
[nan nan nan nan]


---
# 🧪 Small Examples

## Example 1: `np.array()` — Quarterly Sales as a 2D Array
### 2-1. np.array() — 리스트로부터 배열 생성

In [3]:
import numpy as np

# Business: monthly sales by quarter (unit: 10K KRW)
monthly_sales = np.array([
    [1200, 1350, 1100],   # Q1: Jan, Feb, Mar
    [1400, 1600, 1500],   # Q2: Apr, May, Jun
    [1300, 1250, 1450],   # Q3: Jul, Aug, Sep
    [1700, 1800, 2000]    # Q4: Oct, Nov, Dec
])

print("Quarterly monthly sales:\n", monthly_sales)
print("Array shape:", monthly_sales.shape)   # (4, 3) -> 4 quarters x 3 months

Quarterly monthly sales:
 [[1200 1350 1100]
 [1400 1600 1500]
 [1300 1250 1450]
 [1700 1800 2000]]
Array shape: (4, 3)


## Example 2: `np.zeros()` / `np.ones()` — Initializing an Achievement-Rate Tracker
### 2-2. np.zeros() / np.ones() — 0과 1로 채운 배열

In [4]:
import numpy as np

# Business: set up a 12-month achievement-rate tracker
monthly_achievement = np.zeros(12)
print("Initialized 12-month achievement array:", monthly_achievement)

# As real numbers come in, compute achievement against target
actual_sales = np.array([1200, 1350, 1100, 1400, 1600, 1500,
                          1300, 1250, 1450, 1700, 1800, 2000])
target_sales = np.ones(12) * 1500   # every month's target is 1500 (10K KRW)

monthly_achievement = actual_sales / target_sales * 100
print("Monthly achievement (%):", np.round(monthly_achievement, 1))

Initialized 12-month achievement array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Monthly achievement (%): [ 80.   90.   73.3  93.3 106.7 100.   86.7  83.3  96.7 113.3 120.  133.3]


## Example 3: `np.arange()` — Day Index & Price Bins
### 2-3. np.arange() — 규칙적인 간격의 정수 배열

In [5]:
import numpy as np

# Business: a full-year day index
days = np.arange(1, 366)
print("First 10 days of the year:", days[:10])
print("Last 5 days of the year:", days[-5:])

# Business: define price bins — 0 to 1,000,000 KRW, in 100,000 KRW steps
price_bins = np.arange(0, 1_100_000, 100_000)
print("Price bins:", price_bins)

First 10 days of the year: [ 1  2  3  4  5  6  7  8  9 10]
Last 5 days of the year: [361 362 363 364 365]
Price bins: [      0  100000  200000  300000  400000  500000  600000  700000  800000
  900000 1000000]


## Example 4: `np.linspace()` — Discount-Rate Scenarios
### 2-4. np.linspace() — 균등 간격 배열

In [6]:
import numpy as np

# Business: simulate discount rates from 5% to 30% in 6 even steps
discount_rates = np.linspace(0.05, 0.30, 6)
print("Discount scenarios:", np.round(discount_rates, 3))

base_price = 100000
discounted_prices = base_price * (1 - discount_rates)
print("Discounted prices:", discounted_prices)

Discount scenarios: [0.05 0.1  0.15 0.2  0.25 0.3 ]
Discounted prices: [95000. 90000. 85000. 80000. 75000. 70000.]


## Example 5: `np.full()` — Missing-Value Placeholder Array
### 2-5. np.full() — 특정 값으로 채운 배열

In [7]:
import numpy as np

# Business: initialize a year of monthly data as missing, then fill in what you have
monthly_data = np.full(12, np.nan)
monthly_data[:6] = [1200, 1350, 1100, 1400, 1600, 1500]   # only H1 filled in so far

print("Monthly data:", monthly_data)
print("Months with data:", np.sum(~np.isnan(monthly_data)))

Monthly data: [1200. 1350. 1100. 1400. 1600. 1500.   nan   nan   nan   nan   nan   nan]
Months with data: 6


## Example 6: `np.eye()` — Removing Self-Correlation from a Correlation Matrix
### 2-6. np.eye() — 단위 행렬

In [8]:
import numpy as np

# Business: a 3x3 correlation matrix between three metrics
correlation_matrix = np.array([
    [1.00, 0.85, 0.32],
    [0.85, 1.00, 0.67],
    [0.32, 0.67, 1.00]
])

# Subtract the identity matrix to zero out the (always 1.0) self-correlation
no_self_corr = correlation_matrix - np.eye(3)
print("Correlation with self-correlation removed:\n", no_self_corr)

Correlation with self-correlation removed:
 [[0.   0.85 0.32]
 [0.85 0.   0.67]
 [0.32 0.67 0.  ]]


## Example 7: Practice — One Mini-Exercise per Function
### 연습 문제 (Practice Problems, 2-1 ~ 2-6)

**Task / 과제:** This section's original material has one practice problem per subtopic — solve all six below.
이번 섹션은 하위주제마다 연습 문제가 하나씩 있습니다 — 아래 6개를 모두 풀어보세요.

1. **(2-1)** Build a 2D array of weekly visitor counts for 3 regions × 5 weekdays, print its shape.
   3개 지역 × 5개 요일의 주간 방문자 수를 2D 배열로 만들고 shape을 출력하세요.
2. **(2-2)** Create a 4×3 zeros array with `dtype=int`.
   4행 3열의 0 배열을 `dtype=int`로 만드세요.
3. **(2-3)** Create months 1–12 with `np.arange()`.
   `np.arange()`로 1월~12월 배열을 만드세요.
4. **(2-4)** Create 5 evenly spaced achievement levels from 0 to 100 with `np.linspace()`.
   `np.linspace()`로 0~100 사이 5개의 균등한 달성률 기준값을 만드세요.
5. **(2-5)** Create a 12-element array where every value is 20,000,000, with `np.full()`.
   `np.full()`로 12개월 모두 20,000,000인 배열을 만드세요.
6. **(2-6)** Print a 4×4 identity matrix as `dtype=int` with `np.eye()`.
   `np.eye()`로 4×4 단위 행렬을 `dtype=int`로 출력하세요.

Fill in each `________` below, then run the cell.
아래 각 `________`를 채운 후 셀을 실행하세요.

In [12]:
# ✏️ Practice — replace each ________ line below, then run this cell.
# ✏️ 연습 문제 — 아래 각 ________ 줄을 채운 후 셀을 실행하세요.

import numpy as np

print("--- 2-1: np.array() ---")
# TODO: 2D array of weekly visitors — Seoul [100,120,95,130,150], Busan [80,90,85,100,110],
# Daegu [60,75,70,80,90]. Print the array, then its .shape
print(
np.array([
        [100,120,95,130,150],
        [80,90,85,100,110],
        [60,75,70,80,90]
    ]
))

print("\n--- 2-2: np.zeros() ---")
# TODO: a 4x3 zeros array with dtype=int, printed
print(np.zeros((4,3), dtype=int))

print("\n--- 2-3: np.arange() ---")
# TODO: months 1 through 12 using np.arange(), printed
print(np.arange(1,13))

print("\n--- 2-4: np.linspace() ---")
# TODO: 5 evenly spaced values from 0 to 100 using np.linspace(), printed
print(np.linspace(0,100,5))

print("\n--- 2-5: np.full() ---")
# TODO: a 12-element array where every value is 20_000_000, using np.full(), printed
print(np.full(12, 20_000_000))

print("\n--- 2-6: np.eye() ---")
# TODO: a 4x4 identity matrix with dtype=int, using np.eye(), printed
print(np.eye(4, dtype=int))

print("\n✅ Fill in each ________ above with real code, then re-run to see all 6 results.")
print("✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 6개 결과를 모두 볼 수 있습니다.")

--- 2-1: np.array() ---
[[100 120  95 130 150]
 [ 80  90  85 100 110]
 [ 60  75  70  80  90]]

--- 2-2: np.zeros() ---
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

--- 2-3: np.arange() ---
[ 1  2  3  4  5  6  7  8  9 10 11 12]

--- 2-4: np.linspace() ---
[  0.  25.  50.  75. 100.]

--- 2-5: np.full() ---
[20000000 20000000 20000000 20000000 20000000 20000000 20000000 20000000
 20000000 20000000 20000000 20000000]

--- 2-6: np.eye() ---
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

✅ Fill in each ________ above with real code, then re-run to see all 6 results.
✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 6개 결과를 모두 볼 수 있습니다.


---
# ⚠️ Common Mistakes

**Mistake 1 — Ragged nested lists silently become an `object` array.**
If the inner lists you pass to `np.array()` don't all have the same length, NumPy doesn't raise an error — it just falls back to a slow, generic `object` dtype array that loses most of NumPy's speed benefits.  
`np.array()`에 넣는 리스트들의 길이가 서로 다르면 에러가 나지 않고, 느리고 범용적인 `object` dtype 배열이 되어 NumPy의 속도 이점을 대부분 잃게 됩니다.  
✅ **Fix:** Double-check every row has the same length before building a 2D array; a shape mismatch is often a sign of a data problem upstream.  
✅ **해결법:** 2D 배열을 만들기 전에 모든 행의 길이가 같은지 먼저 확인하세요 — shape이 맞지 않는다면 보통 상위 데이터 자체에 문제가 있다는 신호입니다.

**Mistake 2 — `dtype=int` silently truncates decimals.**
`np.array([1.5, 2.7, 3.9], dtype=int)` doesn't round — it truncates toward zero, giving `[1, 2, 3]`. That's quiet data loss if you weren't expecting it.  
`np.array([1.5, 2.7, 3.9], dtype=int)`는 반올림이 아니라 0 방향으로 잘라내어 `[1, 2, 3]`이 됩니다 — 예상하지 못했다면 조용한 데이터 손실입니다.  
✅ **Fix:** Use `np.round()` before converting to `int` if you actually want rounding.  
✅ **해결법:** 반올림을 원한다면 `int`로 변환하기 전에 `np.round()`를 먼저 사용하세요.

**Mistake 3 — Passing shape as separate arguments instead of a tuple.**
`np.zeros(3, 4)` raises a `TypeError` because the second positional argument to `zeros` is `dtype`, not another size. The shape must be one tuple: `np.zeros((3, 4))`.  
`np.zeros(3, 4)`는 `TypeError`를 발생시킵니다 — `zeros`의 두 번째 위치 인자는 크기가 아니라 `dtype`이기 때문입니다. shape은 반드시 하나의 튜플이어야 합니다: `np.zeros((3, 4))`.  
✅ **Fix:** Always wrap multi-dimensional shapes in parentheses: `(rows, cols)`.  
✅ **해결법:** 다차원 shape은 항상 괄호로 감싸세요: `(행, 열)`.

**Mistake 4 — Forgetting the default dtype is `float64`.**
`np.zeros()`, `np.ones()`, and `np.eye()` all default to `float64`, even when you're conceptually thinking in whole numbers — you'll get `1.` instead of `1`.  
`np.zeros()`, `np.ones()`, `np.eye()`는 정수를 생각하고 있어도 기본적으로 `float64`를 반환합니다 — `1`이 아니라 `1.`이 나옵니다.  
✅ **Fix:** Pass `dtype=int` explicitly whenever you need whole numbers.  
✅ **해결법:** 정수가 필요하면 항상 `dtype=int`를 명시적으로 지정하세요.

**Mistake 5 — Assuming `np.arange()`'s stop value is included.**
`np.arange(1, 10)` stops at 9 — the `stop` argument is always excluded, exactly like Python's built-in `range()`.  
`np.arange(1, 10)`은 9에서 끝납니다 — 파이썬 내장 `range()`와 마찬가지로 `stop` 인자는 항상 포함되지 않습니다.  
✅ **Fix:** If you need `stop` included, add one step (`np.arange(1, 11)`) or switch to `np.linspace()`.  
✅ **해결법:** `stop`을 포함해야 한다면 한 스텝을 더하거나(`np.arange(1, 11)`) `np.linspace()`로 바꾸세요.

**Mistake 6 — Trusting a decimal `step` in `np.arange()` for an exact count.**
`np.arange(0, 1, 0.1)` can produce 10 or 11 elements depending on floating-point rounding, because decimal steps accumulate tiny errors.  
`np.arange(0, 1, 0.1)`은 부동소수점 오차가 누적되어 10개가 나올 수도, 11개가 나올 수도 있습니다.  
✅ **Fix:** When you need an exact number of points, use `np.linspace(start, stop, num)` instead — it guarantees the count.  
✅ **해결법:** 정확한 개수가 필요하다면 `np.arange()` 대신 `np.linspace(start, stop, num)`을 사용하세요 — 개수를 보장합니다.

**Mistake 7 — Putting `np.nan` into an integer array.**
`np.nan` only exists as a float — trying to store it in an `int` array raises an error or silently corrupts the value, depending on how you assign it.  
`np.nan`은 float로만 존재합니다 — `int` 배열에 넣으려 하면 에러가 나거나, 대입 방식에 따라 값이 조용히 손상될 수 있습니다.  
✅ **Fix:** Any array that might hold `np.nan` should stay `float` (NumPy's default for `np.full()`/`np.zeros()` already is), never `int`.  
✅ **해결법:** `np.nan`을 담을 가능성이 있는 배열은 항상 `float`로 유지하세요(`np.full()`/`np.zeros()`의 기본값이 이미 float입니다) — 절대 `int`로 만들지 마세요.

---
# 💡 Tips
Useful tips or shortcuts

- Run `.shape` immediately after creating any array — it's the fastest sanity check that you built what you intended.  
배열을 만든 직후 바로 `.shape`을 확인하세요 — 의도한 대로 만들어졌는지 가장 빠르게 확인하는 방법입니다.
- Decide FIRST whether you care about spacing or count: step size in mind → `arange`; exact number of points in mind → `linspace`.  
간격이 중요한지, 개수가 중요한지 먼저 정하세요: 간격(step) 기준이면 `arange`, 정확한 개수 기준이면 `linspace`입니다.
- `np.zeros_like(existing_array)` and `np.ones_like(existing_array)` copy an existing array's shape automatically — handy when you need a same-shaped placeholder without retyping dimensions.  
`np.zeros_like(existing_array)`와 `np.ones_like(existing_array)`는 기존 배열의 shape을 그대로 복사합니다 — 차원을 다시 입력하지 않고 같은 모양의 placeholder가 필요할 때 유용합니다.

---
# 🔗 Related Concepts

```
Section 1 — NumPy Introduction
   (what ndarray is, list vs ndarray)
        ↓
🔵 Section 2 — ndarray Creation   ← you are here
   (array, zeros/ones, arange, linspace, full, eye)
        ↓
Section 3 — Array Attributes
   (.shape, .ndim, .dtype, .size — inspecting what you just created)
        ↓
Sections 4-9 — indexing, manipulation,
   vectorization, aggregation, random/sorting
        ↓
Section 10 — Pandas + NumPy integration
        ↓
Sections 11-12 — Business KPIs, missing values
        ↓
Pandas → SQL → Tableau
```

*How is today's topic connected to other concepts?*

Section 1 explained WHY `ndarray` exists; this section is HOW you actually build one. Every array you create here immediately feeds into Section 3, where you'll inspect its `.shape`, `.dtype`, and `.size` — the natural next question after "I made an array" is always "what does it actually look like?"

섹션 1이 `ndarray`가 왜 존재하는지를 설명했다면, 이번 섹션은 실제로 어떻게 만드는지를 다룹니다. 여기서 만든 모든 배열은 곧바로 섹션 3으로 이어지는데, 그곳에서 `.shape`, `.dtype`, `.size`를 확인하게 됩니다 — "배열을 만들었다" 다음에는 항상 "이게 실제로 어떻게 생겼지?"라는 질문이 자연스럽게 따라옵니다.

---
# 💼 Business Example
*How would a Business Analyst use this?*

**Scenario / 시나리오:**
You're setting up a brand-new monthly sales tracker for a product that just launched. You need: (1) a 12-month array to hold actual sales, starting empty, (2) a day-of-year index for daily-level reporting, (3) evenly spaced discount tiers for an upcoming promotion, and (4) a fixed monthly target array to measure against.  
막 출시된 제품의 월별 매출 트래커를 처음부터 구축하는 상황입니다. 필요한 것: (1) 실제 매출을 담을 12개월짜리 빈 배열, (2) 일별 리포트를 위한 연중 일수 인덱스, (3) 다가오는 프로모션을 위한 균등 간격 할인 단계, (4) 비교 기준이 될 고정 월간 목표 배열.

**To-do / 할 일:**
- [x] Initialize a 12-month sales array with `np.zeros()`.  
`np.zeros()`로 12개월 매출 배열을 초기화합니다.
- [x] Build a day-of-year index with `np.arange()`.  
`np.arange()`로 연중 일수 인덱스를 만듭니다.
- [x] Create 4 evenly spaced discount tiers between 10% and 40% with `np.linspace()`.  
`np.linspace()`로 10%~40% 사이 4단계 할인율을 만듭니다.
- [x] Set every month's target to 15,000,000 KRW with `np.full()`.  
`np.full()`로 매월 목표를 1,500만원으로 설정합니다.

In [10]:
import numpy as np

# 1. Blank 12-month sales tracker
monthly_sales = np.zeros(12)
print("Initial monthly sales:", monthly_sales)

# 2. Day-of-year index for daily reporting
day_index = np.arange(1, 366)
print("Day index sample:", day_index[:5], "...", day_index[-5:])

# 3. Evenly spaced discount tiers for the launch promotion
discount_tiers = np.linspace(0.10, 0.40, 4)
print("Discount tiers:", discount_tiers)

# 4. Fixed monthly target
monthly_target = np.full(12, 15_000_000)
print("Monthly targets:", monthly_target)

# Quick check: how far is month 1 from target once real data comes in?
monthly_sales[0] = 9_500_000  # first month's actual result
gap = monthly_sales[0] - monthly_target[0]
print(f"Month 1 gap vs target: {gap:,.0f} KRW")

Initial monthly sales: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Day index sample: [1 2 3 4 5] ... [361 362 363 364 365]
Discount tiers: [0.1 0.2 0.3 0.4]
Monthly targets: [15000000 15000000 15000000 15000000 15000000 15000000 15000000 15000000
 15000000 15000000 15000000 15000000]
Month 1 gap vs target: -5,500,000 KRW


---
# 📝 Summary
*Write today's concept in 3~5 sentences.*

NumPy offers six core functions to build an `ndarray` without typing every value by hand: `np.array()` converts existing data like a list, `np.zeros()`/`np.ones()` create blank baseline arrays, `np.arange()` builds a step-based sequence (stop excluded), `np.linspace()` builds a count-based sequence (stop included), `np.full()` fills an array with one specific value, and `np.eye()` builds an identity matrix. The pair most likely to cause confusion is `arange` vs `linspace` — one is about spacing, the other about how many points you want — and the most common trap across nearly every function is forgetting the default dtype is `float64`, or forgetting shape must be a tuple. Getting comfortable with all six means you rarely need a manual loop just to set up starting data.

NumPy는 값을 일일이 입력하지 않고도 `ndarray`를 만들 수 있는 6가지 핵심 함수를 제공합니다: `np.array()`는 리스트 같은 기존 데이터를 변환하고, `np.zeros()`/`np.ones()`는 빈 기준 배열을 만들고, `np.arange()`는 간격(step) 기준으로 시퀀스를 만들며(stop 미포함), `np.linspace()`는 개수(count) 기준으로 시퀀스를 만들고(stop 포함), `np.full()`은 특정 값으로 배열을 채우며, `np.eye()`는 단위 행렬을 만듭니다. 가장 헷갈리기 쉬운 조합은 `arange`와 `linspace`인데 — 하나는 간격이, 다른 하나는 원하는 점의 개수가 기준입니다 — 그리고 거의 모든 함수에서 공통적으로 걸리는 함정은 기본 dtype이 `float64`라는 점과 shape이 튜플이어야 한다는 점을 잊는 것입니다. 이 6가지에 익숙해지면 시작 데이터를 준비하기 위해 반복문을 직접 쓸 일이 거의 없어집니다.

---
# 📌 One Sentence Summary
Today's topic in ONE sentence.

> NumPy's six creation functions — `array`, `zeros`/`ones`, `arange`, `linspace`, `full`, `eye` — let you build any starting array without a manual loop, as long as you know whether you care about step size or point count.

> NumPy의 6가지 생성 함수(`array`, `zeros`/`ones`, `arange`, `linspace`, `full`, `eye`)를 사용하면, 간격(step)과 개수(count) 중 무엇이 기준인지만 알면 반복문 없이 원하는 시작 배열을 만들 수 있습니다.

---
# ❓ Review Questions

**Q1.** What's the difference between `np.arange()` and `np.linspace()` in terms of what you specify and whether the stop value is included?  
`np.arange()`와 `np.linspace()`는 무엇을 지정하는지와 stop 값 포함 여부에서 어떻게 다른가요?

`np.arange()` specifies a start, stop, and step, and usually excludes the stop value. `np.linspace()` specifies a start, stop, and number of values, and includes the stop value by default.  
`np.arange()`는 시작값, 끝값, 간격(step)을 지정하고 보통 끝값은 포함하지 않습니다. `np.linspace()`는 시작값, 끝값, 개수(num)를 지정하고 기본적으로 끝값을 포함합니다.

**Q2.** Why does `np.zeros((3, 4))` work but `np.zeros(3, 4)` raise a `TypeError`?  
`np.zeros((3, 4))`는 작동하는데 `np.zeros(3, 4)`는 왜 `TypeError`를 발생시키나요?
`np.zeros()` expects the shape as one argument. (3, 4) is one tuple representing a 3×4 shape, while 3, 4 are interpreted as two separate arguments.  
`np.zeros()`는 배열의 크기(shape)를 하나의 인자로 받습니다. (3, 4)는 하나의 tuple로서 "3행 4열"을 의미하지만, 3, 4는 서로 다른 두 개의 인자로 전달되기 때문에 에러가 발생합니다.

**Q3.** What's the default dtype for `np.zeros()`, `np.ones()`, and `np.eye()`, and how do you override it?  
`np.zeros()`, `np.ones()`, `np.eye()`의 기본 dtype은 무엇이며, 이를 어떻게 바꿀 수 있나요?
The default dtype is float64. You can override it using the dtype argument.  
`np.zeros()`, `np.ones()`, `np.eye()`의 기본 dtype은 float64입니다. dtype 인자를 사용해서 변경할 수 있습니다.

**Q4.** Why would you use `np.full(12, np.nan)` instead of `np.zeros(12)` to initialize a tracker with missing data?  
결측 데이터가 있는 트래커를 초기화할 때 `np.zeros(12)` 대신 `np.full(12, np.nan)`을 쓰는 이유는 무엇인가요?
`np.zeros(12)` uses 0, which is a real numeric value. `np.nan` clearly represents "missing or unknown", so it prevents missing data from being confused with an actual zero.  
`np.zeros(12)`은 0이라는 실제 숫자를 넣기 때문에 "값이 0인 것"과 "아직 값이 없는 것"을 구분할 수 없습니다. `np.nan`은 결측값을 명확하게 나타내므로 둘을 구분할 수 있습니다.

**Q5.** When would `np.eye()` actually come up in BA/DA work, even though it's rarely used directly?  
`np.eye()`가 직접 쓰이는 경우는 드물지만, BA/DA 실무에서는 언제 등장할 수 있나요?
`np.eye()` creates an identity matrix, which is useful in mathematical and statistical operations such as regression, matrix calculations, regularization, and algorithms involving transformations.  
`np.eye()`는 단위 행렬(identity matrix)을 만들며, 회귀분석, 행렬 계산, 정규화(regularization), 각종 수학적 알고리즘에서 사용될 수 있습니다.

---
*📅 Try answering these again in a few days.*