# 📚 Section 5: Boolean Indexing & Fancy Indexing
> Boolean Indexing & Fancy Indexing — Selecting by condition, replacing by condition, and selecting by exact position — all three always return a Copy

---
# 🎯 Learning Objective
Today I want to learn:
- [x] How to filter an array with a condition (Boolean Indexing) using `&`, `|`, `~` instead of `and`/`or`
- [x] How to replace values conditionally with `np.where()`, including nested conditions
- [x] How to select specific positions in a specific order with Fancy Indexing, and why it (like Boolean Indexing) always returns a Copy

---
# 🧠 Concept

## What is it?
*(Explain it in your own words.)*

These are two different ways to select from an array beyond simple position-based indexing/slicing. Boolean Indexing keeps elements where a condition is `True` — you describe WHAT you want, not WHERE it is. Fancy Indexing does the opposite: you give exact positions (as a list or array of integers), in any order, even repeated. `np.where()` sits in between — it doesn't filter, it replaces values based on a condition, like Excel's `IF()`. All three share one crucial trait: unlike slicing, their results are always a Copy, never a View.

이 둘은 단순 위치 기반 인덱싱·슬라이싱을 넘어서는 두 가지 선택 방법입니다. Boolean Indexing은 조건이 `True`인 원소만 남기며 — "어디에 있는지"가 아니라 "무엇을 원하는지"를 서술합니다. Fancy Indexing은 반대로, 정확한 위치를(정수 리스트나 배열로) 순서 상관없이, 심지어 중복도 가능하게 지정합니다. `np.where()`는 그 중간에 있는데 — 필터링이 아니라 조건에 따라 값을 치환합니다. Excel의 `IF()`와 같은 개념입니다. 셋 모두 중요한 공통점이 하나 있습니다: 슬라이싱과 달리 결과는 항상 Copy이며, 절대 View가 아닙니다.

### Three selection tools, side by side / 3가지 선택 도구 비교

| Method / 방법 | What it does / 하는 일 | Returns / 반환 |
|---|---|---|
| Boolean Indexing `arr[arr > 10]` | Filters — keeps matching elements (필터링 — 조건에 맞는 원소만 남김) | Always 1D, always Copy |
| `np.where(cond, a, b)` | Replaces — same shape, new values (치환 — 같은 shape, 새로운 값) | Same shape as input, Copy |
| Fancy Indexing `arr[[0, 2, 4]]` | Selects — exact positions, any order (선택 — 정확한 위치, 순서 자유) | Same length as index list, Copy |

## Why do we use it?
*(When is it useful?)*

Because most real analysis questions aren't "give me row 5" — they're "give me everyone who spent over 300,000" or "give me the top 3 regions." Position-based indexing can't answer those; these three tools can.

대부분의 실제 분석 질문은 "5번째 행을 달라"가 아니라 "30만원 이상 쓴 사람 전부"나 "상위 3개 지역"이기 때문입니다. 위치 기반 인덱싱으로는 이런 질문에 답할 수 없고, 이 3가지 도구가 그 역할을 합니다.

## When is it used in Business Analytics?
*(Real-world use case)*

- Segmenting customers into VIP / regular / at-risk-of-churn by a spend threshold.  
  구매금액 기준으로 고객을 VIP/일반/이탈위험으로 세그먼트할 때.
- Cleaning outliers or negative values by replacing them with 0 or the column mean.   
  이상치나 음수값을 0이나 평균으로 대체해 정제할 때.
- Assigning a grade or label (A/B/C/D, VIP/Gold/Silver) based on a numeric threshold.   
  숫자 기준값에 따라 등급이나 라벨(A/B/C/D, VIP/Gold/Silver)을 부여할 때.
- Pulling the top-N ranked rows after sorting, or re-ordering specific columns for a report.    
  정렬 후 상위 N개 순위 데이터를 꺼내거나, 리포트를 위해 특정 컬럼 순서를 재배열할 때.

---
# 📝 Syntax

## Basic Syntax

In [1]:
import numpy as np

arr = np.array([10, 25, 40, 15, 55, 30])

# Boolean Indexing — filter by condition
print(arr[arr > 20])                    # [25 40 55 30]

# np.where — replace by condition
print(np.where(arr > 20, arr, 0))       # [ 0 25 40  0 55 30]

# Fancy Indexing — select exact positions, any order
print(arr[[4, 0, 2]])                   # [55 10 40]

[25 40 55 30]
[ 0 25 40  0 55 30]
[55 10 40]


## Common Variations

In [2]:
import numpy as np

arr = np.array([10, 25, 40, 15, 55, 30])

# compound conditions need & / | / ~ (NOT Python's and/or/not), and parentheses
print(arr[(arr > 15) & (arr < 50)])     # AND
print(arr[(arr < 15) | (arr > 50)])     # OR
print(arr[~(arr > 30)])                 # NOT

# np.where with just a condition returns matching INDICES, not values
idx = np.where(arr > 20)
print(idx)              # (array([1, 2, 4, 5]),)
print(arr[idx])          # values at those indices

# nested np.where for multi-level labels
label = np.where(arr >= 50, "high", np.where(arr >= 20, "mid", "low"))
print(label)

# Fancy Indexing on a 2D array — pick rows in a custom order
grid = np.array([[1, 2], [3, 4], [5, 6]])
print(grid[[2, 0]])      # rows 2 then 0

[25 40 30]
[10 55]
[10 25 15 30]
(array([1, 2, 4, 5]),)
[25 40 55 30]
['low' 'mid' 'mid' 'low' 'high' 'mid']
[[5 6]
 [1 2]]


---
# 🧪 Small Examples

## Example 1: Boolean Indexing — Segmenting 100 Customers
### 5-1. Boolean Indexing — 조건으로 필터링

In [3]:
import numpy as np

# Business: 100 customers' monthly purchase amount
np.random.seed(42)
purchase = np.random.randint(10000, 500000, size=100)

# VIP: 300,000 or more
vip_mask = purchase >= 300000
vip_sales = purchase[vip_mask]

print(f"Total customers: {purchase.size}")
print(f"VIP customers: {vip_sales.size} ({vip_sales.size / purchase.size * 100:.1f}%)")
print(f"VIP average purchase: {vip_sales.mean():,.0f}")
print(f"VIP max purchase: {vip_sales.max():,.0f}")

# Churn risk: under 50,000
churn_risk = purchase[purchase < 50000]
print(f"\nChurn-risk customers: {churn_risk.size}")

# Regular: 50,000 to under 300,000
regular = purchase[(purchase >= 50000) & (purchase < 300000)]
print(f"Regular customers: {regular.size}")

Total customers: 100
VIP customers: 38 (38.0%)
VIP average purchase: 407,276
VIP max purchase: 499,492

Churn-risk customers: 3
Regular customers: 59


## Example 2: `np.where()` — Cleaning Revenue & Grading Customers
### 5-2. np.where() — 조건에 따라 값 치환

In [4]:
import numpy as np

# Business: clean outliers in revenue, then grade customers by spend
monthly_revenue = np.array([
    1200, 1350, -200, 1400, 99999, 1500,
    1300, 1250, 1450, 1700, -100, 2000
])

# Outlier handling: negative -> 0, over 5000 -> average of the valid values
cleaned = np.where(monthly_revenue < 0, 0, monthly_revenue)
valid_mean = cleaned[cleaned <= 5000].mean()
cleaned = np.where(cleaned > 5000, valid_mean, cleaned)
print("Cleaned revenue:", np.round(cleaned, 0))

# Customer grading
customer_spend = np.array([50000, 320000, 150000, 480000, 95000,
                            280000, 75000, 410000, 30000, 550000])

grade = np.where(customer_spend >= 400000, "VIP",
         np.where(customer_spend >= 200000, "Gold",
         np.where(customer_spend >= 100000, "Silver", "Bronze")))

print("\nCustomer grades:")
for spend, g in zip(customer_spend, grade):
    print(f"  {spend:,} -> {g}")

Cleaned revenue: [1200. 1350.    0. 1400. 1195. 1500. 1300. 1250. 1450. 1700.    0. 2000.]

Customer grades:
  50,000 -> Bronze
  320,000 -> Gold
  150,000 -> Silver
  480,000 -> VIP
  95,000 -> Bronze
  280,000 -> Gold
  75,000 -> Bronze
  410,000 -> VIP
  30,000 -> Bronze
  550,000 -> VIP


## Example 3: Fancy Indexing — Top-3 Regions by Sales
### 5-3. Fancy Indexing — 정수 배열로 여러 인덱스 동시 선택

In [5]:
import numpy as np

# Business: top 3 regions by sales
region_sales = np.array([8500, 3200, 12000, 7800, 15000, 4500, 9200])
region_names = ["Seoul", "Gangwon", "Gyeonggi", "Incheon", "Busan", "Jeonnam", "Gyeongnam"]

# argsort() gives ascending indices -> reverse for descending -> take top 3
sorted_idx = np.argsort(region_sales)[::-1]
top3_idx = sorted_idx[:3]

print("Top 3 region indices:", top3_idx)
print("Top 3 regions:")
for i, idx in enumerate(top3_idx):
    print(f"  #{i+1}: {region_names[idx]} — {region_sales[idx]:,}")

# Business: reorder specific columns for a report
channel_data = np.array([
    [3.2, 4.1, 2.8, 5.0, 2.5],
    [3.4, 4.3, 3.0, 5.2, 2.6],
    [3.1, 4.0, 2.7, 4.9, 2.4],
])
# columns: organic(0), paid_ads(1), sns(2), email(3), direct(4)
paid_email = channel_data[:, [3, 1]]   # email first, then paid_ads
print("\nEmail & paid_ads conversion:\n", paid_email)

Top 3 region indices: [4 2 6]
Top 3 regions:
  #1: Busan — 15,000
  #2: Gyeonggi — 12,000
  #3: Gyeongnam — 9,200

Email & paid_ads conversion:
 [[5.  4.1]
 [5.2 4.3]
 [4.9 4. ]]


## Example 4: Practice — One Mini-Exercise per Subtopic
### 연습 문제 (Practice Problems, 5-1 ~ 5-3)

**Task / 과제:** This section's original material has one practice problem per subtopic — solve all three below.     
이번 섹션은 하위주제마다 연습 문제가 하나씩 있습니다 — 아래 3개를 모두 풀어보세요.

1. **(5-1)** From 30 random product prices, print count + average price for (a) ≥50,000, (b) 20,000–80,000, (c) <10,000 or >100,000.      
   30개 랜덤 상품 가격에서 (a) 5만원 이상, (b) 2만~8만원, (c) 1만원 미만이거나 10만원 초과인 상품의 개수와 평균 가격을 출력하세요.
2. **(5-2)** From a 10-item inventory array, label each item `"reorder"` if quantity <10, `"excess"` if >50, else `"normal"`.    
   10개 제품 재고 배열에서 재고가 10개 미만이면 `"reorder"`, 50개 초과이면 `"excess"`, 나머지는 `"normal"`로 분류하세요.
3. **(5-3)** From a 10-product sales array, print the index and sales of the top 3 products (using `argsort()`).     
   10개 제품 판매량 배열에서 `argsort()`를 사용해 상위 3개 제품의 인덱스와 판매량을 출력하세요.

Fill in each `________` below, then run the cell.
아래 각 `________`를 채운 후 셀을 실행하세요.

In [13]:
# ✏️ Practice — replace each ________ line below, then run this cell.
# ✏️ 연습 문제 — 아래 각 ________ 줄을 채운 후 셀을 실행하세요.

import numpy as np

print("--- 5-1: Boolean Indexing ---")
# TODO: np.random.seed(0); prices = np.random.randint(5000, 150000, size=30)
# then print count+average for >=50000, 20000-80000, and (<10000 or >100000)
np.random.seed(0)
prices = np.random.randint(5000, 150000, size=30)
a = prices[prices >= 50000]
b = prices[(prices >= 20000) & (prices <= 80000)]
c = prices[(prices < 10000) | (prices > 100000)]
print(a.size, a.mean())
print(b.size, b.mean())
print(c.size, c.mean())

print("\n--- 5-2: np.where() ---")
# TODO: inventory = [5,30,75,12,3,50,80,25,8,45] -> label each "reorder"/"excess"/"normal"
inventory = np.array([5,30,75,12,3,50,80,25,8,45])
cleaned = np.where(inventory < 10, "reorder", np.where(inventory > 50, "excess", "normal"))
print(cleaned)

print("\n--- 5-3: Fancy Indexing ---")
# TODO: product_sales = [320,150,480,290,610,175,540,220,390,410] -> print top-3 index & sales
product_sales = np.array([320,150,480,290,610,175,540,220,390,410])
top3_idx = np.argsort(product_sales)[::-1][:3]
print(top3_idx)
print(product_sales[top3_idx])

print("\n✅ Fill in each ________ above with real code, then re-run to see all 3 results.")
print("✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 3개 결과를 모두 볼 수 있습니다.")

--- 5-1: Boolean Indexing ---
25 101913.8
10 54704.3
14 122343.21428571429

--- 5-2: np.where() ---
['reorder' 'normal' 'excess' 'normal' 'reorder' 'normal' 'excess' 'normal'
 'reorder' 'normal']

--- 5-3: Fancy Indexing ---
[4 6 2]
[610 540 480]

✅ Fill in each ________ above with real code, then re-run to see all 3 results.
✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 3개 결과를 모두 볼 수 있습니다.


---
# ⚠️ Common Mistakes

**Mistake 1 — Using Python's `and` / `or` on NumPy boolean arrays.**  
`sales[(sales > 1300) and (sales < 1500)]` raises an error — Python's `and`/`or` expect a single `True`/`False`, not an array of many.      
`sales[(sales > 1300) and (sales < 1500)]`는 에러가 납니다 — Python의 `and`/`or`는 배열 여러 개가 아니라 단일 `True`/`False`를 기대합니다.      
✅ **Fix:** Use `&` (and), `|` (or), `~` (not) for NumPy boolean arrays instead.  
✅ **해결법:** NumPy 불리언 배열에는 `&`(and), `|`(or), `~`(not)를 사용하세요.  

**Mistake 2 — Forgetting parentheses around each condition.**  
`sales[sales > 1300 & sales < 1500]` fails or misbehaves — `&` binds tighter than `>`, so Python evaluates it in the wrong order.  
`sales[sales > 1300 & sales < 1500]`는 실패하거나 잘못 동작합니다 — `&`가 `>`보다 우선순위가 높아서 Python이 잘못된 순서로 계산합니다.  
✅ **Fix:** Always wrap each condition in its own parentheses: `sales[(sales > 1300) & (sales < 1500)]`.  
✅ **해결법:** 항상 각 조건을 괄호로 감싸세요: `sales[(sales > 1300) & (sales < 1500)]`.  

**Mistake 3 — Confusing `np.where(cond)` with `np.where(cond, a, b)`.**  
With ONE argument, `np.where(scores >= 60)` returns the matching INDICES as a tuple — not the values, and not a boolean mask. Only the 3-argument form replaces values.  
인수가 하나뿐인 `np.where(scores >= 60)`은 값이나 불리언 마스크가 아니라 조건을 만족하는 인덱스를 튜플로 반환합니다. 값을 치환하는 것은 인수가 3개인 형태뿐입니다.  
✅ **Fix:** Need indices? Use one argument. Need replaced values? Always supply all three: `np.where(cond, value_if_true, value_if_false)`.  
✅ **해결법:** 인덱스가 필요하면 인수 1개, 치환된 값이 필요하면 항상 3개를 모두 넣으세요: `np.where(cond, 참일때값, 거짓일때값)`.  

**Mistake 4 — Nesting `np.where()` too many levels deep.**  
Three or more nested `np.where()` calls (for multi-tier grading, say) become hard to read and easy to get the order wrong in.  
`np.where()`를 3단계 이상 중첩하면(다단계 등급 분류 등) 가독성이 떨어지고 순서를 헷갈리기 쉽습니다.  
✅ **Fix:** Switch to `np.select(conditions, choices, default=...)` once you have more than 2-3 tiers — it lists every condition and choice as a flat, readable pair.  
✅ **해결법:** 등급 구간이 2~3단계를 넘어가면 `np.select(conditions, choices, default=...)`로 바꾸세요 — 모든 조건과 결과를 평평하고 읽기 쉬운 쌍으로 나열합니다.  

**Mistake 5 — Expecting `matrix[[0, 2], [1, 3]]` to return a sub-matrix.**  
This actually pairs up the lists element-by-element and returns just 2 values: `(row0, col1)` and `(row2, col3)` — not a 2×2 block.  
이 표현은 실제로는 리스트를 원소별로 짝지어 값 2개만 반환합니다: `(row0, col1)`과 `(row2, col3)` — 2×2 블록이 아닙니다.  
✅ **Fix:** For an actual sub-matrix of specific rows AND columns, use `matrix[np.ix_([0, 2], [1, 3])]` instead.  
✅ **해결법:** 특정 행과 열의 실제 서브 행렬이 필요하다면 대신 `matrix[np.ix_([0, 2], [1, 3])]`을 사용하세요.  

**Mistake 6 — Letting a Fancy Indexing index run out of range.**  
If your index array contains a number ≥ the array's length (or too negative), NumPy raises an `IndexError` rather than silently skipping it.  
인덱스 배열에 배열 길이 이상(또는 너무 작은 음수)인 값이 있으면, NumPy는 조용히 건너뛰지 않고 `IndexError`를 발생시킵니다.  
✅ **Fix:** If your index list is computed (not hardcoded), sanity-check it against `.size` or `.shape` before indexing.  
✅ **해결법:** 인덱스 목록이 계산된 값이라면(하드코딩이 아니라면), 인덱싱 전에 `.size`나 `.shape`으로 범위를 미리 확인하세요.  

**Mistake 7 — Assuming Boolean/Fancy Indexing results are Views, like slices.**  
Unlike Section 4's slices, both Boolean Indexing and Fancy Indexing ALWAYS return a Copy — modifying the result never touches the original array.   
섹션 4의 슬라이스와 달리, Boolean Indexing과 Fancy Indexing은 둘 다 항상 Copy를 반환합니다 — 결과를 수정해도 원본 배열은 절대 바뀌지 않습니다.  
✅ **Fix:** This is good news, not a bug — you can filter-then-modify freely. Just don't expect changes to a filtered/fancy-indexed result to propagate back to the source.  
✅ **해결법:** 이건 버그가 아니라 좋은 소식입니다 — 필터링 후 자유롭게 수정해도 됩니다. 다만 필터링·Fancy Indexing 결과의 변경이 원본에 반영될 거라 기대하지는 마세요.  `

---
# 💡 Tips
Useful tips or shortcuts

- When you only need to know WHERE a condition is true (not the values themselves), `np.where(condition)` alone is enough — no need to also filter with `arr[mask]`.  
  조건이 어디서 참인지만 알면 될 때는 `np.where(condition)`만으로 충분합니다 — 굳이 `arr[mask]`로 다시 필터링할 필요 없습니다.  
- `np.select(conditions, choices, default=...)` is the cleaner alternative once you have more than 2-3 grading tiers.   
  등급 구간이 2~3단계를 넘어가면 `np.select(conditions, choices, default=...)`가 더 깔끔한 대안입니다.    
- `np.argsort(arr)[::-1][:n]` is the standard "top N" idiom — memorize it once, reuse it everywhere.    
  `np.argsort(arr)[::-1][:n]`는 "상위 N개" 관용구입니다 — 한 번 외워두면 어디서나 재사용할 수 있습니다.   

---
# 🔗 Related Concepts

```
Section 4 — Indexing & Slicing
   (position-based: single elements & ranges, View)
        ↓
🔵 Section 5 — Boolean & Fancy Indexing   ← you are here
   (condition-based & explicit-position selection, always Copy)
        ↓
Section 6 — Array Manipulation
   (reshape, flatten, transpose, concatenate, split)
        ↓
Sections 7-9 — vectorization/broadcasting,
   aggregation, random/sorting
        ↓
Section 10 — Pandas + NumPy integration
        ↓
Sections 11-12 — Business KPIs, missing values
        ↓
Pandas → SQL → Tableau
```

*How is today's topic connected to other concepts?*

Section 4 selected by POSITION; this section selects by CONDITION (Boolean Indexing, `np.where`) or by explicit POSITION LIST (Fancy Indexing) — and unlike Section 4's slices, everything here is a safe-to-modify Copy. This is also the exact mechanism Pandas' `.loc[]` and boolean filtering (`df[df['col'] > x]`) use internally, so this section is a direct preview of how filtering works once you move to Pandas.

섹션 4가 위치로 선택했다면, 이번 섹션은 조건(Boolean Indexing, `np.where`)이나 명시적 위치 목록(Fancy Indexing)으로 선택합니다 — 그리고 섹션 4의 슬라이스와 달리, 여기서는 전부 수정해도 안전한 Copy입니다. 이는 Pandas의 `.loc[]`와 불리언 필터링(`df[df['col'] > x]`)이 내부적으로 사용하는 방식과 정확히 같아서, 이번 섹션은 나중에 Pandas로 넘어갔을 때 필터링이 어떻게 작동하는지 미리 보는 것과 같습니다.

---
# 💼 Business Example
*How would a Business Analyst use this?*

**Scenario / 시나리오:**
You're preparing a monthly customer report. You need to (1) segment customers into VIP/Regular/Churn-risk by spend, (2) clean negative revenue values, and (3) pull the top-3 performing regions to highlight in the report.        
월간 고객 리포트를 준비하는 상황입니다. 필요한 것: (1) 구매금액 기준으로 고객을 VIP/일반/이탈위험으로 세그먼트, (2) 음수 매출값 정제, (3) 리포트에 강조할 상위 3개 지역 추출.       

**To-do / 할 일:**
- [x] Use Boolean Indexing to split customers into VIP / regular / churn-risk.      
      Boolean Indexing으로 고객을 VIP/일반/이탈위험으로 나눕니다. 
- [x] Use `np.where()` to zero out negative revenue values.       
      `np.where()`로 음수 매출값을 0으로 만듭니다.    
- [x] Use Fancy Indexing + `argsort()` to pull the top-3 regions.             
      Fancy Indexing과 `argsort()`로 상위 3개 지역을 추출합니다.

In [14]:
import numpy as np

# 1. Customer segmentation
np.random.seed(1)
spend = np.random.randint(10000, 600000, size=20)

vip = spend[spend >= 400000]
regular = spend[(spend >= 100000) & (spend < 400000)]
churn_risk = spend[spend < 100000]
print(f"VIP: {vip.size}, Regular: {regular.size}, Churn-risk: {churn_risk.size}")

# 2. Revenue cleanup
revenue = np.array([1200, -300, 1500, 1100, -50, 1800])
cleaned_revenue = np.where(revenue < 0, 0, revenue)
print("Cleaned revenue:", cleaned_revenue)

# 3. Top-3 regions
region_sales = np.array([4200, 8800, 3100, 9600, 5400, 7200])
region_names = ["A", "B", "C", "D", "E", "F"]
top3_idx = np.argsort(region_sales)[::-1][:3]
print("\nTop 3 regions:")
for rank, idx in enumerate(top3_idx, start=1):
    print(f"  #{rank}: {region_names[idx]} — {region_sales[idx]:,}")

VIP: 9, Regular: 8, Churn-risk: 3
Cleaned revenue: [1200    0 1500 1100    0 1800]

Top 3 regions:
  #1: D — 9,600
  #2: B — 8,800
  #3: F — 7,200


---
# 📝 Summary
*Write today's concept in 3~5 sentences.*

Boolean Indexing filters an array down to the elements where a condition is `True` (`arr[arr > x]`), using `&`/`|`/`~` instead of Python's `and`/`or`/`not`. `np.where(cond, a, b)` doesn't filter — it replaces, keeping the original shape, and works exactly like Excel's `IF()`. Fancy Indexing selects exact positions from a list of integers, in any order, with repeats allowed. All three share one property that sets them apart from slicing: their results are always a Copy, so you can modify them freely without touching the source array. Together, these three tools answer the "give me everyone/everything that matches X" questions that position-based indexing can't.

Boolean Indexing은 조건이 `True`인 원소만 남기는 필터링이며(`arr[arr > x]`), Python의 `and`/`or`/`not` 대신 `&`/`|`/`~`를 사용합니다. `np.where(cond, a, b)`는 필터링이 아니라 치환이며, 원래 shape을 유지하고 Excel의 `IF()`와 똑같이 동작합니다. Fancy Indexing은 정수 리스트로 정확한 위치를 순서 상관없이, 중복도 허용해서 선택합니다. 셋 다 슬라이싱과 구별되는 공통 속성이 하나 있습니다: 결과가 항상 Copy이므로 원본을 건드리지 않고 자유롭게 수정할 수 있습니다. 이 3가지 도구는 위치 기반 인덱싱으로는 답할 수 없는 "X에 해당하는 전부를 달라" 유형의 질문에 답합니다.

---
# 📌 One Sentence Summary
Today's topic in ONE sentence.

> Boolean Indexing filters by condition, `np.where()` replaces by condition, and Fancy Indexing selects exact positions in any order — and all three, unlike slicing, always return a safe-to-modify Copy.

> Boolean Indexing은 조건으로 필터링하고, `np.where()`는 조건으로 치환하며, Fancy Indexing은 정확한 위치를 순서 상관없이 선택합니다 — 그리고 슬라이싱과 달리 셋 다 항상 수정해도 안전한 Copy를 반환합니다.

---
# ❓ Review Questions

**Q1.** Why does `sales[(sales > 1300) and (sales < 1500)]` raise an error, and what should you write instead?
`sales[(sales > 1300) and (sales < 1500)]`은 왜 에러가 나며, 대신 무엇을 써야 하나요?
and expects single Boolean values, but NumPy comparisons produce arrays of Boolean values. Use & for element-wise comparison.  
and는 하나의 Boolean 값을 기대하지만 NumPy의 비교 결과는 여러 개의 Boolean으로 이루어진 배열이기 때문에 에러가 발생합니다. 원소별 비교에는 &를 사용합니다.

**Q2.** What does `np.where(scores >= 60)` return with only ONE argument, versus `np.where(scores >= 60, scores, 0)` with three?
`np.where(scores >= 60)`처럼 인수 하나만 줬을 때와, `np.where(scores >= 60, scores, 0)`처럼 3개를 줬을 때 각각 무엇을 반환하나요?
With one argument, np.where() returns the indices where the condition is True. With three arguments, it returns values from scores where the condition is True, and 0 otherwise.
인수가 하나이면 조건이 True인 인덱스를 반환합니다. 세 개를 넣으면 조건이 True일 때 scores의 값을 사용하고, False일 때 0을 사용합니다.

**Q3.** What's the difference between `sales[idx]` (Fancy Indexing) and `sales[start:stop]` (slicing) in terms of View vs Copy?
`sales[idx]`(Fancy Indexing)와 `sales[start:stop]`(슬라이싱)은 View/Copy 측면에서 어떻게 다른가요?
Fancy indexing returns a copy, while slicing usually returns a view.  
Fancy Indexing은 Copy를 반환하고, 일반적인 slicing은 View를 반환합니다.

**Q4.** What idiom pulls the indices of the top-3 largest values in an array?
배열에서 가장 큰 값 상위 3개의 인덱스를 꺼내는 관용구는 무엇인가요?
A common idiom is np.argsort(arr)[-3:][::-1].  
배열에서 가장 큰 값 3개의 인덱스를 얻으려면 보통 np.argsort(arr)[-3:][::-1]을 사용합니다.

**Q5.** Why does `matrix[[0, 2], [1, 3]]` NOT return a 2×2 sub-matrix, and what would you use instead if you wanted one?
`matrix[[0, 2], [1, 3]]`은 왜 2×2 서브 행렬을 반환하지 않으며, 서브 행렬을 원한다면 대신 무엇을 사용해야 하나요?
Fancy indexing pairs the row indices and column indices element by element. So matrix[[0, 2], [1, 3]] selects (0,1) and (2,3), not every combination.  
Fancy Indexing에서는 행 인덱스와 열 인덱스를 서로 짝지어서 선택합니다. 따라서 matrix[[0, 2], [1, 3]]은 (0,1)과 (2,3) 두 위치만 가져옵니다.

---
*📅 Try answering these again in a few days.*