# 📚 Section 6: Array Manipulation
> 배열 조작 — Reshaping, flattening, transposing, joining, and splitting arrays without changing a single value

---
# 🎯 Learning Objective
Today I want to learn:
- [x] How to change an array's shape with `.reshape()` (including the `-1` auto-dimension trick) without changing its data
- [x] The difference between `.flatten()` (always Copy) and `.ravel()` (View when possible), and between `.reshape()`/`.T` (View) and `.concatenate()`/`.vstack()`/`.hstack()`/`.split()` (Copy)
- [x] How to join arrays together (`concatenate`, `vstack`, `hstack`) and split them apart (`split`, `vsplit`, `hsplit`)

---
# 🧠 Concept

## What is it?
*(Explain it in your own words.)*

Array manipulation reshapes or restructures an array WITHOUT changing any of its underlying values — turning a flat list into a grid, flipping rows and columns, gluing several arrays into one, or breaking one array into several. It's the glue step between raw data and whatever comes next: a Pandas DataFrame, a chart, or a machine learning model's expected input shape.

배열 조작은 원본 값은 전혀 바꾸지 않고 배열의 형태나 구조만 바꾸는 작업입니다 — 1차원 리스트를 격자로 바꾸거나, 행과 열을 뒤집거나, 여러 배열을 하나로 합치거나, 하나의 배열을 여러 개로 나누는 것입니다. 원본 데이터와 그 다음 단계(Pandas DataFrame, 차트, 머신러닝 모델이 기대하는 입력 shape) 사이를 이어주는 접착제 역할을 합니다.

### Which function, what does it return? / 어떤 함수가 무엇을 반환하나?

| Function / 함수 | What it does / 하는 일 | Returns / 반환 |
|---|---|---|
| `.reshape()` | Change shape, same data (shape만 변경, 데이터는 동일) | View (usually) |
| `.flatten()` | Collapse to 1D, always independent (1D로 축소, 항상 독립) | Copy |
| `.ravel()` | Collapse to 1D, shares memory when possible (1D로 축소, 가능하면 메모리 공유) | View (usually) |
| `.T` / `.transpose()` | Swap rows and columns (행과 열을 교환) | View |
| `np.concatenate()` | Join arrays along an axis (축을 따라 배열 연결) | Copy |
| `np.vstack()` / `np.hstack()` | Join vertically / horizontally (수직/수평 연결) | Copy |
| `np.split()` / `vsplit()` / `hsplit()` | Break one array into several (하나를 여러 개로 분할) | List of Copies |

## Why do we use it?
*(When is it useful?)*

Because data almost never arrives in the exact shape you need it in — a flat CSV column needs to become a 2D grid, two half-year arrays need to become one full year, or a matrix needs its rows and columns swapped before a correlation calculation.

데이터는 필요한 형태로 딱 맞춰서 들어오는 경우가 거의 없기 때문입니다 — 1차원 CSV 컬럼을 2D 격자로 바꿔야 하거나, 반기 두 배열을 하나의 연간 배열로 합쳐야 하거나, 상관계수 계산 전에 행과 열을 바꿔야 할 때가 있습니다.

## When is it used in Business Analytics?
*(Real-world use case)*

- Reshaping a flat monthly array into a quarter×month grid for period-based reporting.  
  분기별 리포팅을 위해 1차원 월별 배열을 분기×월 격자로 재구성할 때.
- Flattening a 2D table into 1D before passing it to a histogram or an overall summary stat.  
  히스토그램이나 전체 요약 통계에 넘기기 전 2D 테이블을 1D로 펼칠 때.
- Transposing a pivot table to switch which dimension is rows vs. columns.  
  피벗 테이블에서 행/열 방향을 바꿀 때.
- Merging separately-loaded monthly/regional files into one array, or splitting one array into train/validation/test sets.  
  개별적으로 불러온 월별·지역별 파일을 하나로 합치거나, 하나의 배열을 train/validation/test로 나눌 때.

---
# 📝 Syntax

## Basic Syntax

In [1]:
import numpy as np

a = np.arange(12)

print(a.reshape(3, 4))         # 1D -> 2D, same 12 values
print(a.flatten())              # any shape -> 1D, always a Copy
print(a.reshape(3, 4).T)        # swap rows and columns

b = np.arange(12, 24).reshape(3, 4)
print(np.concatenate([a.reshape(3, 4), b], axis=0))   # stack along rows
print(np.split(a, 3))                                   # break into 3 equal pieces

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


## Common Variations

In [2]:
import numpy as np

a = np.arange(12)

# -1 means "figure this dimension out for me"
print(a.reshape(3, -1).shape)    # (3, 4)
print(a.reshape(-1, 1).shape)    # (12, 1) -> column vector

# ravel vs flatten — same values, different memory behavior
r = a.reshape(3, 4).ravel()
f = a.reshape(3, 4).flatten()
print(r.base is not None, f.base is None)   # True True -> r shares memory, f doesn't

# vstack/hstack read more naturally than concatenate
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.vstack([x, y]))     # stacks into 2D: [[1 2 3] [4 5 6]]
print(np.hstack([x, y]))     # stays 1D: [1 2 3 4 5 6]

# vsplit/hsplit are the readable shortcuts for split(..., axis=0/1)
grid = np.arange(16).reshape(4, 4)
top, bottom = np.vsplit(grid, 2)
left, right = np.hsplit(grid, 2)

(3, 4)
(12, 1)
True True
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


---
# 🧪 Small Examples

## Example 1: `reshape()` — Monthly Sales into a Quarterly Grid
### 6-1. reshape() — 형태 변환

In [3]:
import numpy as np

# Business: reorganize 12 months into 4 quarters x 3 months
monthly_sales = np.array([
    1200, 1350, 1100,   # Q1
    1400, 1600, 1500,   # Q2
    1300, 1250, 1450,   # Q3
    1700, 1800, 2000    # Q4
])

quarterly = monthly_sales.reshape(4, 3)
print("Sales by quarter:\n", quarterly)

quarters = ["Q1", "Q2", "Q3", "Q4"]
for i, q in enumerate(quarters):
    print(f"{q} total: {quarterly[i].sum():,}")

# Business: reshape a flat feature array into an ML input shape
raw_features = np.random.randn(5000)   # 1000 customers x 5 features, collected flat
X = raw_features.reshape(-1, 5)         # -1 lets NumPy compute rows: 5000/5 = 1000
print(f"\nML input shape: {X.shape}")

Sales by quarter:
 [[1200 1350 1100]
 [1400 1600 1500]
 [1300 1250 1450]
 [1700 1800 2000]]
Q1 total: 3,650
Q2 total: 4,500
Q3 total: 4,000
Q4 total: 5,500

ML input shape: (1000, 5)


## Example 2: `flatten()` vs `ravel()` — Annual Stats from a Quarterly Grid
### 6-2. flatten() vs ravel() — 1D로 펼치기

In [4]:
import numpy as np

# Business: flatten a quarter x month grid to compute annual stats
quarterly_sales = np.array([
    [1200, 1350, 1100],   # Q1
    [1400, 1600, 1500],   # Q2
    [1300, 1250, 1450],   # Q3
    [1700, 1800, 2000]    # Q4
])

all_monthly = quarterly_sales.flatten()   # Copy — safe, original untouched
print("All 12 months:", all_monthly)
print(f"\nAnnual total: {all_monthly.sum():,}")
print(f"Monthly average: {all_monthly.mean():.0f}")
print(f"Best month: {all_monthly.max():,}")
print(f"Worst month: {all_monthly.min():,}")

# See the View behavior of ravel() for comparison
rav = quarterly_sales.ravel()
rav[0] = 999
print("\nOriginal after modifying ravel() result:\n", quarterly_sales)   # changed!

All 12 months: [1200 1350 1100 1400 1600 1500 1300 1250 1450 1700 1800 2000]

Annual total: 17,650
Monthly average: 1471
Best month: 2,000
Worst month: 1,100

Original after modifying ravel() result:
 [[ 999 1350 1100]
 [1400 1600 1500]
 [1300 1250 1450]
 [1700 1800 2000]]


## Example 3: `.T` — Pivoting Region×Quarter into Quarter×Region
### 6-3. transpose() / .T — 행렬 전치

In [5]:
import numpy as np

# Business: original has rows=region, cols=quarter — flip it
region_quarter = np.array([
    [1200, 1400, 1300, 1700],   # Seoul: Q1-Q4
    [800, 950, 870, 1100],      # Busan: Q1-Q4
    [600, 720, 680, 900]        # Daegu: Q1-Q4
])
print("Original (region x quarter):", region_quarter.shape)

quarter_region = region_quarter.T
print("Transposed (quarter x region):", quarter_region.shape)

quarters = ["Q1", "Q2", "Q3", "Q4"]
for i, q in enumerate(quarters):
    print(f"{q} nationwide total: {quarter_region[i].sum():,}")

Original (region x quarter): (3, 4)
Transposed (quarter x region): (4, 3)
Q1 nationwide total: 2,600
Q2 nationwide total: 3,070
Q3 nationwide total: 2,850
Q4 nationwide total: 3,700


## Example 4: `np.concatenate()` — Merging H1 and H2 into a Full Year
### 6-4. np.concatenate() — 배열 연결

In [6]:
import numpy as np

# Business: 3 regions x 6 months, first half and second half of the year
h1_sales = np.array([
    [1200, 1350, 1100, 1400, 1600, 1500],   # Seoul: Jan-Jun
    [800, 850, 780, 900, 950, 920],         # Busan: Jan-Jun
    [600, 620, 590, 650, 680, 660]          # Daegu: Jan-Jun
])
h2_sales = np.array([
    [1300, 1250, 1450, 1700, 1800, 2000],   # Seoul: Jul-Dec
    [870, 840, 910, 980, 1020, 990],        # Busan: Jul-Dec
    [640, 620, 670, 710, 730, 700]          # Daegu: Jul-Dec
])

# Join along columns (axis=1) -> full year per region
annual = np.concatenate([h1_sales, h2_sales], axis=1)
print("Annual shape:", annual.shape)   # (3, 12)

regions = ["Seoul", "Busan", "Daegu"]
for i, region in enumerate(regions):
    print(f"{region} annual total: {annual[i].sum():,}, monthly avg: {annual[i].mean():.0f}")

Annual shape: (3, 12)
Seoul annual total: 17,650, monthly avg: 1471
Busan annual total: 10,810, monthly avg: 901
Daegu annual total: 7,870, monthly avg: 656


## Example 5: `vstack()` / `hstack()` — Adding a Region and a Metric
### 6-5. np.vstack() / np.hstack() — 수직/수평 스택

In [7]:
import numpy as np

# Business: add a new region as a row (vstack)
existing_data = np.array([
    [1200, 1400, 1300, 1700],   # Seoul Q1-Q4
    [800, 950, 870, 1100]       # Busan Q1-Q4
])
new_region = np.array([[600, 720, 680, 900]])   # Daegu, newly added

all_data = np.vstack([existing_data, new_region])
print("After adding a region:\n", all_data)
print("shape:", all_data.shape)

# Business: add a new metric as a column (hstack)
sales_visitors = np.array([[1200, 3200], [800, 2100], [600, 1800]])
conversion = np.array([[3.8], [3.5], [3.2]])   # already a column vector

full_data = np.hstack([sales_visitors, conversion])
print("\nAfter adding conversion rate:\n", full_data)
print("shape:", full_data.shape)

After adding a region:
 [[1200 1400 1300 1700]
 [ 800  950  870 1100]
 [ 600  720  680  900]]
shape: (3, 4)

After adding conversion rate:
 [[1200.  3200.     3.8]
 [ 800.  2100.     3.5]
 [ 600.  1800.     3.2]]
shape: (3, 3)


## Example 6: `split()` / `vsplit()` — H1/H2 and Train/Val/Test
### 6-6. np.split() / vsplit() / hsplit() — 배열 분할

In [8]:
import numpy as np

# Business: split 12 months of [sales, visitors, conversion] into H1/H2
monthly = np.array([
    [1200, 3200, 38], [1350, 3500, 39], [1100, 2800, 39], [1400, 3700, 38],
    [1600, 4100, 39], [1500, 3900, 38], [1300, 3300, 39], [1250, 3100, 40],
    [1450, 3600, 40], [1700, 4200, 40], [1800, 4400, 41], [2000, 4800, 42]
])

h1, h2 = np.vsplit(monthly, 2)
print(f"H1 total sales: {h1[:, 0].sum():,}")
print(f"H2 total sales: {h2[:, 0].sum():,}")

# Business: split 1000 samples into train/val/test (60/20/20)
data = np.arange(1000)
train, val, test = np.split(data, [600, 800])
print(f"\ntrain: {len(train)}, val: {len(val)}, test: {len(test)}")

H1 total sales: 8,150
H2 total sales: 9,500

train: 600, val: 200, test: 200


## Example 7: Practice — One Mini-Exercise per Function
### 연습 문제 (Practice Problems, 6-1 ~ 6-6)

**Task / 과제:** This section's original material has one practice problem per subtopic — solve all six below.  
이번 섹션은 하위주제마다 연습 문제가 하나씩 있습니다 — 아래 6개를 모두 풀어보세요.

1. **(6-1)** A 1–24 array → reshape to (a) 6×4, (b) 4×6, (c) 2×3×4, (d) auto-rows × 8-cols.  
   1~24 배열을 (a) 6×4, (b) 4×6, (c) 2×3×4, (d) 행 자동×열 8로 reshape하세요.
2. **(6-2)** A 4×3 array → compare `flatten()` vs `ravel()` by modifying each and checking whether the original changed.  
   4×3 배열에서 `flatten()`과 `ravel()` 각각을 수정한 뒤 원본이 바뀌는지 비교하세요.
3. **(6-3)** A 5-month × 3-channel ad-cost table → transpose to channel×month, print each channel's monthly average.  
   5개월×3채널 광고비 테이블을 채널×월로 전치하고, 채널별 월평균을 출력하세요.
4. **(6-4)** Two (3,3) arrays → `concatenate` along `axis=0`, print the result shape.  
   (3,3) 배열 2개를 `axis=0`으로 연결하고 결과 shape을 출력하세요.
5. **(6-5)** Two (3,3) arrays → `vstack` to (6,3) and `hstack` to (3,6), print both shapes.  
   (3,3) 배열 2개를 `vstack`으로 (6,3), `hstack`으로 (3,6)으로 합치고 두 shape을 모두 출력하세요.
6. **(6-6)** A 12×4 array → (a) split into 3 equal row-groups, (b) split at row indices [4, 9], print all shapes.  
   12×4 배열을 (a) 행 방향 3등분, (b) 인덱스 [4, 9]에서 분할하고 각 shape을 출력하세요.

Fill in each `________` below, then run the cell.  
아래 각 `________`를 채운 후 셀을 실행하세요.

In [11]:
# ✏️ Practice — replace each ________ line below, then run this cell.
# ✏️ 연습 문제 — 아래 각 ________ 줄을 채운 후 셀을 실행하세요.

import numpy as np

print("--- 6-1: reshape() ---")
# TODO: a = np.arange(1,25) -> print .shape for reshape(6,4), (4,6), (2,3,4), (-1,8)
a = np.arange(1,25)
print(a.shape)
print(a.reshape(6,4).shape)
print(a.reshape(4,6).shape)
print(a.reshape(2,3,4).shape)
print(a.reshape(-1,8).shape)

print("\n--- 6-2: flatten() vs ravel() ---")
# TODO: m = np.arange(12).reshape(4,3) -> modify flatten() and ravel() results, print m both times
m = np.arange(12).reshape(4,3)
print(m.flatten())
print(m.ravel())

print("\n--- 6-3: transpose() ---")
# TODO: 5x3 ad_cost array -> transpose, print each of the 3 channels' row mean
ad_cost = np.random.randn(5,3)
print(ad_cost.T)
print(ad_cost.T.mean(axis=1))

print("\n--- 6-4: concatenate() ---")
# TODO: two (3,3) arrays -> np.concatenate(..., axis=0), print result .shape
a = np.arange(9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
print(np.concatenate([a,b], axis=0).shape)

print("\n--- 6-5: vstack()/hstack() ---")
# TODO: same two (3,3) arrays -> print vstack shape and hstack shape
a = np.arange(9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
print(np.vstack([a,b]).shape)
print(np.hstack([a,b]).shape)

print("\n--- 6-6: split()/vsplit() ---")
# TODO: m2 = np.arange(48).reshape(12,4) -> print shapes for vsplit(m2,3) and split(m2,[4,9],axis=0)
m2 = np.arange(48).reshape(12,4)
print(np.vsplit(m2,3))
print(np.split(m2,[4,9],axis=0))

print("\n✅ Fill in each ________ above with real code, then re-run to see all 6 results.")
print("✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 6개 결과를 모두 볼 수 있습니다.")

--- 6-1: reshape() ---
(24,)
(6, 4)
(4, 6)
(2, 3, 4)
(3, 8)

--- 6-2: flatten() vs ravel() ---
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

--- 6-3: transpose() ---
[[ 0.97450076  0.60938646 -1.23533562 -0.10229358 -1.88834026]
 [-0.04047326 -0.17224335  0.72431776 -0.66304892 -0.6023076 ]
 [ 1.0353685   0.1186258   0.30075947 -1.84165424 -0.61466669]]
[-0.32841645 -0.15075107 -0.20031343]

--- 6-4: concatenate() ---
(6, 3)

--- 6-5: vstack()/hstack() ---
(6, 3)
(3, 6)

--- 6-6: split()/vsplit() ---
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]]), array([[32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23],
   

---
# ⚠️ Common Mistakes

**Mistake 1 — Reshaping into a size that doesn't match.**  
`np.arange(12).reshape(3, 5)` fails because `3 × 5 = 15 ≠ 12` — the total element count must stay exactly the same before and after any reshape.  
`np.arange(12).reshape(3, 5)`는 `3 × 5 = 15 ≠ 12`이기 때문에 실패합니다 — reshape 전후로 전체 원소 개수는 정확히 같아야 합니다.  
✅ **Fix:** Before reshaping, confirm the target dimensions multiply to the original `.size`.  
✅ **해결법:** reshape하기 전, 목표 차원들을 곱한 값이 원본 `.size`와 같은지 먼저 확인하세요.

**Mistake 2 — Using `-1` in more than one dimension.**  
`reshape(-1, -1)` raises a `ValueError` — NumPy can only auto-compute ONE unknown dimension at a time, since two unknowns have infinite solutions.  
`reshape(-1, -1)`은 `ValueError`를 발생시킵니다 — 미지수가 2개면 해가 무한히 많아지므로, NumPy는 한 번에 하나의 차원만 자동 계산할 수 있습니다.  
✅ **Fix:** Always specify every dimension except exactly one when using `-1`.  
✅ **해결법:** `-1`을 사용할 때는 정확히 하나를 제외한 모든 차원을 명시하세요.  

**Mistake 3 — Forgetting `reshape()` and `.T` return a View by default.**  
Modifying the result of `.reshape(...)` or `.T` can silently change the original array too — the same View behavior you saw with slicing in Section 4.  
`.reshape(...)`나 `.T`의 결과를 수정하면 원본 배열도 조용히 바뀔 수 있습니다 — 섹션 4의 슬라이싱에서 본 것과 같은 View 동작입니다.  
✅ **Fix:** If you need an independent result, chain `.copy()`: `arr.reshape(3, 4).copy()`.  
✅ **해결법:** 독립적인 결과가 필요하다면 `.copy()`를 이어붙이세요: `arr.reshape(3, 4).copy()`.

**Mistake 4 — Mixing up `flatten()` and `ravel()`.**  
They produce the same values, but `ravel()` shares memory with the original whenever it can (View), while `flatten()` never does (always Copy) — modifying a `ravel()` result can surprise you by changing the source array.  
둘은 같은 값을 만들지만, `ravel()`은 가능할 때마다 원본과 메모리를 공유하고(View), `flatten()`은 절대 공유하지 않습니다(항상 Copy) — `ravel()` 결과를 수정하면 원본이 예상 밖으로 바뀔 수 있습니다.  
✅ **Fix:** Default to `.flatten()` unless you specifically need `ravel()`'s memory savings.  
✅ **해결법:** `ravel()`의 메모리 절약이 특별히 필요한 게 아니라면 기본적으로 `.flatten()`을 사용하세요.

**Mistake 5 — Expecting `.T` to do something on a 1D array.**  
`np.array([1, 2, 3]).T` returns the exact same 1D array, unchanged — a 1D array has no rows/columns to swap.  
`np.array([1, 2, 3]).T`는 바뀐 것 없이 정확히 같은 1D 배열을 반환합니다 — 1D 배열에는 바꿀 행·열이 없습니다.  
✅ **Fix:** To actually get a column vector, `reshape(-1, 1)` FIRST, then `.T` if needed.  
✅ **해결법:** 실제로 열벡터가 필요하다면 먼저 `reshape(-1, 1)`을 한 뒤 필요하면 `.T`를 쓰세요.

**Mistake 6 — Joining arrays whose non-joining dimension doesn't match.**  
`np.concatenate([a, b], axis=0)` requires `a` and `b` to have the SAME number of columns — joining along rows doesn't fix a column-count mismatch. The same applies to `vstack` (matching columns) and `hstack` (matching rows).  
`np.concatenate([a, b], axis=0)`는 `a`와 `b`의 열 개수가 반드시 같아야 합니다 — 행 방향으로 합친다고 해서 열 개수 불일치가 해결되지는 않습니다. `vstack`(열 개수 일치)과 `hstack`(행 개수 일치)도 마찬가지입니다.  
✅ **Fix:** Before joining, check `.shape` on both arrays and confirm the non-joining dimension matches exactly.  
✅ **해결법:** 합치기 전에 두 배열의 `.shape`을 확인해서 합치지 않는 쪽 차원이 정확히 일치하는지 확인하세요.  

**Mistake 7 — Passing a 1D array straight into `hstack()` with a 2D array.**  
`np.hstack([2D_array, 1D_array])` often raises a dimension-mismatch error, since the 1D array doesn't have the matching row structure.  
`np.hstack([2D_배열, 1D_배열])`은 1D 배열이 맞는 행 구조를 가지고 있지 않아서 흔히 차원 불일치 에러를 냅니다.  
✅ **Fix:** Reshape the 1D array into a column vector first — `arr_1d.reshape(-1, 1)` — before `hstack`-ing it with a 2D array.  
✅ **해결법:** 2D 배열과 `hstack`하기 전에 1D 배열을 먼저 열벡터로 reshape하세요 — `arr_1d.reshape(-1, 1)`.

**Mistake 8 — Calling `np.split(arr, n)` when the size doesn't divide evenly.**  
`np.split(arr, 3)` requires the array's length to be exactly divisible by 3 (same for `vsplit`/`hsplit`'s `n`) — otherwise it raises a `ValueError`.  
`np.split(arr, 3)`은 배열 길이가 정확히 3으로 나누어떨어져야 합니다(`vsplit`/`hsplit`의 `n`도 동일) — 그렇지 않으면 `ValueError`가 발생합니다.  
✅ **Fix:** For uneven splits, pass an explicit list of split-point indices instead: `np.split(arr, [4, 9])`.  
✅ **해결법:** 불균등하게 나눠야 한다면 대신 분할 지점 인덱스 리스트를 명시하세요: `np.split(arr, [4, 9])`.

---
# 💡 Tips
Useful tips or shortcuts

- Print `.shape` before AND after any reshape/transpose/concatenate — it's the fastest way to confirm you got the structure you meant to.  
  reshape/transpose/concatenate 전후로 `.shape`을 출력해보세요 — 의도한 구조가 나왔는지 가장 빠르게 확인하는 방법입니다.  
- When in doubt about Copy vs View after a manipulation, default to the SAFER option (`.flatten()` over `.ravel()`, `.reshape(...).copy()` over a bare `.reshape(...)`) unless you specifically need the memory savings.  
  조작 후 Copy인지 View인지 확신이 안 서면, 메모리 절약이 특별히 필요한 게 아니라면 더 안전한 쪽(`.ravel()`보다 `.flatten()`, `.reshape(...)`보다 `.reshape(...).copy()`)을 기본값으로 쓰세요.  
- `reshape(-1, 1)` (column vector) is worth memorizing on sight — it shows up constantly right before Broadcasting (Section 7).  
  `reshape(-1, 1)`(열벡터)는 보자마자 알아볼 정도로 외워두면 좋습니다 — 섹션 7의 Broadcasting 직전에 계속 등장합니다.

---
# 🔗 Related Concepts

```
Section 5 — Boolean & Fancy Indexing
   (selecting elements by condition or position)
        ↓
🔵 Section 6 — Array Manipulation   ← you are here
   (reshape, flatten/ravel, transpose, concatenate, stack, split)
        ↓
Section 7 — Vectorization & Broadcasting
   (operating on differently-shaped arrays together)
        ↓
Sections 8-9 — aggregation, random/sorting
        ↓
Section 10 — Pandas + NumPy integration
        ↓
Sections 11-12 — Business KPIs, missing values
        ↓
Pandas → SQL → Tableau
```

*How is today's topic connected to other concepts?*

Sections 4-5 selected pieces OF an array; this section reshapes the WHOLE array's structure. The `reshape(-1, 1)` column-vector trick you just learned is the direct setup for Section 7's Broadcasting, where arrays of different shapes need to line up before an operation can run between them.

섹션 4-5가 배열의 일부를 선택하는 방법이었다면, 이번 섹션은 배열 전체의 구조를 바꾸는 방법입니다. 방금 배운 `reshape(-1, 1)` 열벡터 트릭은 섹션 7의 Broadcasting을 위한 직접적인 준비 과정으로, 서로 다른 shape의 배열들이 연산되기 전에 형태를 맞춰야 하기 때문입니다.

---
# 💼 Business Example
*How would a Business Analyst use this?*

**Scenario / 시나리오:**
You've collected 24 months of sales data as one flat array. You need to (1) reshape it into a year×month grid, (2) transpose a separate region×quarter table for a different report, (3) merge H1 data with H2 data, and (4) split a customer dataset into training and test sets for a churn model.  
24개월치 매출 데이터를 하나의 1차원 배열로 수집했습니다. 필요한 것: (1) 연도×월 격자로 reshape, (2) 다른 리포트를 위해 별도의 지역×분기 테이블을 전치, (3) 상반기 데이터와 하반기 데이터를 병합, (4) 이탈 예측 모델을 위해 고객 데이터를 train/test로 분할.

**To-do / 할 일:**  
- [x] Reshape 24 flat months into a (2, 12) year×month grid.  
      24개월 1차원 데이터를 (2, 12) 연도×월 격자로 reshape합니다.  
- [x] Transpose a region×quarter table into quarter×region.  
      지역×분기 테이블을 분기×지역으로 전치합니다.  
- [x] Concatenate two half-year arrays into one full year.  
      두 반기 배열을 하나의 연간 배열로 연결합니다.  
- [x] Split a customer array into 80% train / 20% test.  
      고객 배열을 train 80% / test 20%로 분할합니다.

In [12]:
import numpy as np

# 1. Flat 24 months -> 2 years x 12 months
flat_sales = np.arange(1000, 1000 + 24 * 50, 50)   # 24 sample monthly values
by_year = flat_sales.reshape(2, 12)
print("Year x month shape:", by_year.shape)
print("Year 1 total:", by_year[0].sum(), "| Year 2 total:", by_year[1].sum())

# 2. Transpose region x quarter
region_quarter = np.array([[1200, 1400, 1300, 1700], [800, 950, 870, 1100]])
quarter_region = region_quarter.T
print("\nTransposed shape:", quarter_region.shape)

# 3. Merge H1 + H2
h1 = np.array([[1200, 1350, 1100]])
h2 = np.array([[1700, 1800, 2000]])
full_year = np.concatenate([h1, h2], axis=1)
print("\nMerged shape:", full_year.shape, "->", full_year)

# 4. Train/test split (80/20) for a churn model
customers = np.arange(500)
train, test = np.split(customers, [400])
print(f"\ntrain: {len(train)}, test: {len(test)}")

Year x month shape: (2, 12)
Year 1 total: 15300 | Year 2 total: 22500

Transposed shape: (4, 2)

Merged shape: (1, 6) -> [[1200 1350 1100 1700 1800 2000]]

train: 400, test: 100


---
# 📝 Summary
*Write today's concept in 3~5 sentences.*

Array manipulation restructures data without touching its values: `.reshape()` changes shape (View, using `-1` to auto-compute a dimension), `.flatten()`/`.ravel()` collapse to 1D (always-Copy vs. View-when-possible), `.T`/`.transpose()` swaps rows and columns (View, and does nothing on a 1D array), `.concatenate()`/`.vstack()`/`.hstack()` join arrays together (Copy), and `.split()`/`.vsplit()`/`.hsplit()` break one array into several (Copy). The two things worth remembering above the rest: total element count must stay the same through any reshape, and whether you get a View or a Copy determines whether modifying the result is safe.

배열 조작은 값은 건드리지 않고 데이터의 구조만 바꿉니다: `.reshape()`는 shape을 바꾸고(View, `-1`로 차원 자동 계산), `.flatten()`/`.ravel()`은 1D로 축소하며(항상 Copy vs. 가능하면 View), `.T`/`.transpose()`는 행과 열을 바꾸고(View, 1D 배열에는 효과 없음), `.concatenate()`/`.vstack()`/`.hstack()`은 배열을 합치며(Copy), `.split()`/`.vsplit()`/`.hsplit()`은 하나의 배열을 여러 개로 나눕니다(Copy). 무엇보다 기억할 두 가지: reshape 전후로 전체 원소 개수는 항상 같아야 하고, View인지 Copy인지가 결과를 수정해도 안전한지를 결정합니다.

---
# 📌 One Sentence Summary
Today's topic in ONE sentence.

> Array manipulation — reshape, flatten/ravel, transpose, concatenate/stack, split — restructures data without changing a single value, and whether each operation returns a View or a Copy determines whether it's safe to modify the result.

> 배열 조작(reshape, flatten/ravel, transpose, concatenate/stack, split)은 값은 하나도 바꾸지 않고 데이터 구조만 바꾸며, 각 연산이 View를 반환하는지 Copy를 반환하는지가 결과를 수정해도 안전한지를 결정합니다.

---
# ❓ Review Questions

**Q1.** Why does `np.arange(12).reshape(3, 5)` raise a `ValueError`, and what rule does it violate?  
`np.arange(12).reshape(3, 5)`는 왜 `ValueError`를 발생시키며, 어떤 규칙을 위반하나요?

np.arange(12) has 12 elements, but (3, 5) requires 15 elements. The total number of elements must stay the same when using reshape().  
np.arange(12)에는 원소가 12개 있지만 (3, 5)는 15개의 원소가 필요합니다. reshape()할 때는 전체 원소 개수가 반드시 같아야 합니다.

**Q2.** What's the key difference between `.flatten()` and `.ravel()`, and which is the "safer default"?  
`.flatten()`과 `.ravel()`의 핵심 차이는 무엇이며, 어느 쪽이 "더 안전한 기본값"인가요?

flatten() always returns a copy, while ravel() returns a view when possible. Therefore, flatten() is the safer default when you want an independent array.  
flatten()은 항상 Copy를 반환하고, ravel()은 가능하면 View를 반환합니다. 따라서 원본 배열에 영향을 주지 않는 독립적인 배열이 필요하다면 flatten()이 더 안전한 기본값입니다.

**Q3.** What happens when you call `.T` on a 1D array, and how do you actually get a column vector from one?  
1D 배열에 `.T`를 호출하면 어떻게 되며, 실제로 열벡터를 얻으려면 어떻게 해야 하나요?

The transpose of a 1D array does nothing because a 1D array has only one dimension. To create a column vector, reshape it to (n, 1).  
1D 배열은 차원이 하나뿐이므로 .T를 사용해도 아무 변화가 없습니다. 실제 열벡터를 만들려면 (n, 1) 형태로 reshape()해야 합니다.

**Q4.** When joining two 2D arrays, what's the difference between `axis=0` and `axis=1` in `np.concatenate()`?  
두 2D 배열을 합칠 때, `np.concatenate()`의 `axis=0`과 `axis=1`은 어떻게 다른가요?

axis=0 joins arrays vertically by adding rows, while axis=1 joins them horizontally by adding columns.  
axis=0은 배열을 세로 방향으로 붙여 행을 추가하고, axis=1은 가로 방향으로 붙여 열을 추가합니다.

**Q5.** What's the difference between `np.split(arr, 3)` and `np.split(arr, [4, 9])`?  
`np.split(arr, 3)`과 `np.split(arr, [4, 9])`는 어떻게 다른가요?

np.split(arr, 3) divides the array into 3 equal parts, while np.split(arr, [4, 9]) splits at the specified indices.  
np.split(arr, 3)은 배열을 3개의 동일한 크기 부분으로 나누고, np.split(arr, [4, 9])은 인덱스 4와 9를 기준으로 나눕니다.

---
*📅 Try answering these again in a few days.*