# 📚 Section 8: Aggregation
> Aggregation (집계 함수) — Summarizing many values into one: sum, mean/median, std/var, min/max, cumulative totals, and percentiles

---
# 🎯 Learning Objective
Today I want to learn:
- [x] How `axis=0` vs `axis=1` changes the direction of an aggregation (and how to remember which is which)
- [x] The difference between mean and median (and why median is more robust to outliers), and between `std`/`var` (and `ddof=0` vs `ddof=1`)
- [x] How to find extreme values and their positions (`min`/`max` vs `argmin`/`argmax`), running totals (`cumsum`/`cumprod`), and rank-based cutoffs (`percentile`/`quantile`)

---
# 🧠 Concept

## What is it?
*(Explain it in your own words.)*

Aggregation functions summarize many values in an array down to one (or fewer) values — a total, an average, a spread, an extreme, a running total, or a rank cutoff. The single most important thing to get right is the `axis` parameter: it decides which direction gets "collapsed."

집계 함수는 배열의 여러 값을 하나(또는 더 적은 개수)의 값으로 요약합니다 — 합계, 평균, 퍼짐 정도, 극값, 누적값, 순위 기준값 등입니다. 가장 중요하게 짚고 넘어가야 할 것은 `axis` 파라미터입니다 — 어느 방향이 "축소"되는지를 결정합니다.

### The `axis` direction rule (get this right first) / `axis` 방향 규칙 (가장 먼저 익혀야 할 것)
- No `axis` → collapses EVERYTHING into one number (axis 없음 → 전체가 하나의 값으로)
- `axis=0` → collapses ROWS; result has one value per COLUMN (`axis=0` → 행이 축소, 결과는 열 개수만큼)
- `axis=1` → collapses COLUMNS; result has one value per ROW (`axis=1` → 열이 축소, 결과는 행 개수만큼)
- Memory aid: a `(4, 3)` array with `axis=0` gives shape `(3,)`; with `axis=1` gives shape `(4,)` — the axis NUMBER is the dimension that DISAPPEARS.

### Six aggregation tools, by the question they answer / 답하는 질문별 6가지 집계 도구

| Function / 함수 | Answers / 답하는 질문 |
|---|---|
| `np.sum()` | What's the total? (합계는?) |
| `np.mean()` / `np.median()` | What's typical? (대표값은?) |
| `np.std()` / `np.var()` | How spread out is it? (얼마나 퍼져있나?) |
| `np.min()` / `max()` / `argmin()` / `argmax()` | What's the extreme, and where? (극값과 그 위치는?) |
| `np.cumsum()` / `np.cumprod()` | What's the running total? (누적값은?) |
| `np.percentile()` / `np.quantile()` | Where does this rank? (몇 번째 순위에 있나?) |

## Why do we use it?
*(When is it useful?)*

Because a KPI dashboard is fundamentally a collection of aggregations — a total, an average, a best/worst, a YTD figure — and getting the `axis` direction right (or wrong) is the difference between "sales by month" and "sales by region" from the exact same array.

KPI 대시보드는 본질적으로 집계값의 모음이기 때문입니다 — 합계, 평균, 최고/최저, YTD 수치 등입니다. `axis` 방향을 제대로 맞추는지(또는 틀리는지)가 완전히 같은 배열에서 "월별 매출"이 나오느냐 "지역별 매출"이 나오느냐를 결정합니다.

## When is it used in Business Analytics?
*(Real-world use case)*

- Rolling up daily/monthly data into quarterly and annual totals, per region/channel/product.  
  일별·월별 데이터를 지역/채널/상품별 분기·연간 합계로 집계할 때.
- Choosing mean vs median to summarize revenue or salary data that has outliers.  
  이상치가 있는 매출·연봉 데이터를 평균 또는 중앙값으로 요약할 때.
- Measuring which channel or region has the most stable (lowest std/CV) performance.  
  어떤 채널·지역이 가장 안정적인(표준편차·변동계수가 낮은) 성과를 내는지 측정할 때.
- Tracking YTD progress against a target, and classifying customers into percentile-based tiers (top 20%, bottom 30%).  
  목표 대비 YTD 진행 상황을 추적하고, 고객을 백분위 기준 등급(상위 20%, 하위 30%)으로 분류할 때.

---
# 📝 Syntax

## Basic Syntax

In [1]:
import numpy as np

sales = np.array([[1200, 1350, 1100], [1400, 1600, 1500], [1300, 1250, 1450]])

print(np.sum(sales))              # total (no axis)
print(np.mean(sales, axis=0))     # per-column mean
print(np.std(sales, axis=1))      # per-row std
print(np.max(sales), np.argmax(sales))   # value and flattened position
print(np.cumsum([1200, 1350, 1100]))     # running total
print(np.percentile(sales, 75))          # 75th percentile

12150
[1300. 1400. 1350.]
[102.74023338  81.64965809  84.98365856]
1600 4
[1200 2550 3650]
1450.0


## Common Variations

In [2]:
import numpy as np

sales = np.array([[1200, 1350, 1100], [1400, 1600, 1500], [1300, 1250, 1450]])

# keepdims=True preserves the collapsed dimension as size 1 (useful for Broadcasting)
print(np.sum(sales, axis=1, keepdims=True).shape)   # (3, 1) instead of (3,)

# ddof matters for std/var: population (0, default) vs sample (1)
data = np.array([12, 15, 11, 14, 13])
print(np.std(data, ddof=0), np.std(data, ddof=1))

# argmin/argmax need axis on 2D, or they flatten first
print(np.argmin(sales))            # flattened index
print(np.argmin(sales, axis=1))    # per-row index

# percentile (0-100) vs quantile (0.0-1.0) — same result, different scale
print(np.percentile(data, 50), np.quantile(data, 0.50))

(3, 1)
1.4142135623730951 1.5811388300841898
2
[2 0 1]
13.0 13.0


---
# 🧪 Small Examples

## Example 1: `np.sum()` — Regional Totals and the Best Month
### 8-1. np.sum() — 행/열 방향 합계

In [3]:
import numpy as np

# Business: 3 regions x 12 months, various sums
np.random.seed(1)
region_monthly = np.random.randint(800, 2000, size=(3, 12))
regions = ["Seoul", "Busan", "Daegu"]
months = [f"M{m}" for m in range(1, 13)]

# Annual total per region (axis=1 -> collapses months)
annual_by_region = np.sum(region_monthly, axis=1)
for region, total in zip(regions, annual_by_region):
    print(f"{region} annual total: {total:,}")

# Total across regions per month (axis=0 -> collapses regions), then find the best month
monthly_total = np.sum(region_monthly, axis=0)
best_month_idx = np.argmax(monthly_total)
print(f"\nBest month: {months[best_month_idx]} ({monthly_total[best_month_idx]:,})")

# keepdims=True: each region-month's share of the grand total
total_all = np.sum(region_monthly, keepdims=True)   # shape (1, 1)
share = region_monthly / total_all * 100
print("\nShare of total (%):\n", np.round(share, 1))

Seoul annual total: 17,306
Busan annual total: 17,354
Daegu annual total: 16,234

Best month: M1 (5,406)

Share of total (%):
 [[3.7 2.  3.7 3.4 3.  3.2 3.5 1.9 1.8 3.  2.6 2.3]
 [3.4 2.5 3.4 2.1 2.9 2.4 2.7 2.7 3.5 3.1 3.8 1.8]
 [3.6 2.2 3.2 2.6 2.2 2.  3.  2.8 2.4 2.8 2.5 2.6]]


## Example 2: `mean()` vs `median()` — Why 1000 Customers Need Both
### 8-2. np.mean() / np.median() — 평균과 중앙값

In [4]:
import numpy as np

# Business: 1000 customers, 950 regular + 50 VIP (heavy outliers)
np.random.seed(42)
purchases = np.concatenate([
    np.random.normal(150000, 50000, 950),
    np.random.normal(2000000, 500000, 50)
])
purchases = np.abs(purchases).astype(int)

mean_val = np.mean(purchases)
median_val = np.median(purchases)
gap = (mean_val - median_val) / median_val * 100

print(f"Customers: {len(purchases):,}")
print(f"Mean purchase: {mean_val:,.0f}")
print(f"Median purchase: {median_val:,.0f}")
print(f"Mean-median gap: {gap:.1f}%")

if gap > 20:
    print("-> Mean is much higher than median = high-spending outliers pulling it up")
    print("-> Median is the more representative figure for the typical customer")

Customers: 1,000
Mean purchase: 243,604
Median purchase: 153,980
Mean-median gap: 58.2%
-> Mean is much higher than median = high-spending outliers pulling it up
-> Median is the more representative figure for the typical customer


## Example 3: `std()` / `var()` — Which Channel Is More Stable?
### 8-3. np.std() / np.var() — 표준편차와 분산

In [5]:
import numpy as np

# Business: 3 channels' monthly ROAS — compare volatility
channel_roas = np.array([
    [3.2, 3.5, 2.9, 3.8, 3.1, 4.0, 3.3, 3.6, 2.8, 4.2, 3.9, 3.4],   # search ads
    [2.1, 5.2, 1.8, 6.1, 2.3, 5.8, 1.9, 5.5, 2.0, 6.3, 5.1, 2.2],   # SNS (volatile)
    [3.8, 3.9, 3.7, 4.0, 3.8, 3.9, 3.8, 4.1, 3.7, 4.0, 3.9, 3.8],   # email (stable)
])
channels = ["Search Ads", "SNS", "Email"]

for i, ch in enumerate(channels):
    mean = np.mean(channel_roas[i])
    std = np.std(channel_roas[i])
    cv = std / mean * 100   # coefficient of variation
    print(f"{ch:12s} — mean: {mean:.2f}x  std: {std:.2f}  CV: {cv:.1f}%")

# Outlier detection via Z-score (|z| > 2)
flat_roas = channel_roas.flatten()
z_scores = (flat_roas - flat_roas.mean()) / flat_roas.std()
outliers = flat_roas[np.abs(z_scores) > 2]
print(f"\nZ-score outliers (|z|>2): {outliers}")

Search Ads   — mean: 3.47x  std: 0.42  CV: 12.2%
SNS          — mean: 3.86x  std: 1.84  CV: 47.7%
Email        — mean: 3.87x  std: 0.12  CV: 3.0%

Z-score outliers (|z|>2): [6.1 6.3]


## Example 4: `argmax()` — Auto-Detecting the Best Channel Each Month
### 8-4. np.min() / np.max() / np.argmin() / np.argmax()

In [6]:
import numpy as np

# Business: 5 channels x 12 months conversion rate — find best/worst automatically
np.random.seed(10)
conversion = np.random.uniform(1.5, 6.0, size=(5, 12))
channels = ["Search", "Display", "SNS", "Email", "Direct"]
months = [f"M{m}" for m in range(1, 13)]

channel_avg = np.mean(conversion, axis=1)
best_idx, worst_idx = np.argmax(channel_avg), np.argmin(channel_avg)

print(f"Best channel: {channels[best_idx]} (avg {channel_avg[best_idx]:.2f}%)")
print(f"Worst channel: {channels[worst_idx]} (avg {channel_avg[worst_idx]:.2f}%)")

# Best channel PER MONTH (axis=0 argmax -> one winner per column)
best_per_month = np.argmax(conversion, axis=0)
print("\nBest channel by month:")
for m, ch_idx in zip(months, best_per_month):
    print(f"  {m}: {channels[ch_idx]}")

Best channel: Email (avg 3.87%)
Worst channel: Search (avg 3.66%)

Best channel by month:
  M1: Search
  M2: Email
  M3: Display
  M4: Search
  M5: Direct
  M6: Email
  M7: Display
  M8: Direct
  M9: Direct
  M10: Email
  M11: Direct
  M12: Search


## Example 5: `cumsum()` — YTD Actual vs Target Tracker
### 8-5. np.cumsum() / np.cumprod() — 누적 합계/곱

In [7]:
import numpy as np

# Business: YTD actual vs target dashboard
monthly_actual = np.array([1200, 1350, 1100, 1400, 1600, 1500,
                            1300, 1250, 1450, 1700, 1800, 2000])
monthly_target = np.full(12, 1500)

ytd_actual = np.cumsum(monthly_actual)
ytd_target = np.cumsum(monthly_target)
ytd_gap = ytd_actual - ytd_target

months = [f"M{m}" for m in range(1, 13)]
print(f"{'Month':>6} {'YTD Actual':>12} {'YTD Target':>12} {'Gap':>10}")
for m, a, t, g in zip(months, ytd_actual, ytd_target, ytd_gap):
    status = "OK" if g >= 0 else "behind"
    print(f"{m:>6} {a:>12,} {t:>12,} {g:>+10,} ({status})")

 Month   YTD Actual   YTD Target        Gap
    M1        1,200        1,500       -300 (behind)
    M2        2,550        3,000       -450 (behind)
    M3        3,650        4,500       -850 (behind)
    M4        5,050        6,000       -950 (behind)
    M5        6,650        7,500       -850 (behind)
    M6        8,150        9,000       -850 (behind)
    M7        9,450       10,500     -1,050 (behind)
    M8       10,700       12,000     -1,300 (behind)
    M9       12,150       13,500     -1,350 (behind)
   M10       13,850       15,000     -1,150 (behind)
   M11       15,650       16,500       -850 (behind)
   M12       17,650       18,000       -350 (behind)


## Example 6: `percentile()` — Grading Customers into Bronze/Silver/Gold
### 8-6. np.percentile() / np.quantile() — 분위수

In [8]:
import numpy as np

# Business: percentile-based customer tiers
np.random.seed(0)
purchase = np.random.exponential(100000, size=10000).astype(int) + 10000

p33 = np.percentile(purchase, 33)
p67 = np.percentile(purchase, 67)

bronze = purchase[purchase <= p33]
silver = purchase[(purchase > p33) & (purchase <= p67)]
gold = purchase[purchase > p67]

print(f"Bottom 33% cutoff: {p33:,.0f}")
print(f"Top 33% cutoff: {p67:,.0f}")
print(f"\nBronze: {len(bronze):,} customers (avg {bronze.mean():,.0f})")
print(f"Silver: {len(silver):,} customers (avg {silver.mean():,.0f})")
print(f"Gold: {len(gold):,} customers (avg {gold.mean():,.0f})")

# 5-number summary (classic EDA / interview question)
five_sum = np.percentile(purchase, [0, 25, 50, 75, 100])
for label, val in zip(["Min", "Q1", "Median", "Q3", "Max"], five_sum):
    print(f"  {label:6s}: {val:,.0f}")

Bottom 33% cutoff: 49,221
Top 33% cutoff: 119,777

Bronze: 3,300 customers (avg 28,167)
Silver: 3,400 customers (avg 80,248)
Gold: 3,300 customers (avg 219,678)
  Min   : 10,007
  Q1    : 38,144
  Median: 78,023
  Q3    : 147,948
  Max   : 1,082,227


## Example 7: Practice — One Mini-Exercise per Function
### 연습 문제 (Practice Problems, 8-1 ~ 8-6)

**Task / 과제:** This section's original material has one practice problem per subtopic — solve all six below.
이번 섹션은 하위주제마다 연습 문제가 하나씩 있습니다 — 아래 6개를 모두 풀어보세요.

1. **(8-1)** 5 products × 6 months sales → (a) per-product half-year total, (b) per-month total across products, (c) grand total.  
   5개 상품×6개월 판매량에서 (a) 상품별 반기 합계, (b) 월별 전 상품 합계, (c) 전체 합계를 계산하세요.
2. **(8-2)** 7 salaries with 1 huge outlier → compute mean, median, and mean excluding the outlier.  
   큰 이상치 1개가 포함된 7명의 연봉에서 평균, 중앙값, 이상치 제외 평균을 계산하세요.
3. **(8-3)** Two locations' daily visitors → compare stability via std and CV (coefficient of variation).  
   두 지점의 일별 방문자 데이터에서 표준편차와 변동계수로 안정성을 비교하세요.
4. **(8-4)** 10 products' sales → print the name + value of the best-selling and worst-selling product.  
   10개 상품 판매량에서 최고·최저 판매 상품의 이름과 판매량을 출력하세요.
5. **(8-5)** Quarterly new signups → cumulative total per quarter + achievement rate against an annual target of 5000.  
   분기별 신규 가입자에서 분기별 누적 가입자 수와 연간 목표 5000명 대비 달성률을 출력하세요.
6. **(8-6)** 100 random sales values with 2 injected outliers → IQR-based outlier detection.  
   2개의 이상치가 삽입된 100개 랜덤 매출 데이터에서 IQR 기준 이상치를 탐지하세요. 

Fill in each `________` below, then run the cell.
아래 각 `________`를 채운 후 셀을 실행하세요.

In [12]:
# ✏️ Practice — replace each ________ line below, then run this cell.
# ✏️ 연습 문제 — 아래 각 ________ 줄을 채운 후 셀을 실행하세요.

import numpy as np

print("--- 8-1: sum() ---")
# TODO: np.random.seed(5); sales=np.random.randint(100,500,size=(5,6))
# print sales.sum(axis=1), sales.sum(axis=0), sales.sum()
np.random.seed(5)
sales=np.random.randint(100,500,size=(5,6))

print(sales.sum(axis=1))
print(sales.sum(axis=0))
print(sales.sum())

print("\n--- 8-2: mean()/median() ---")
# TODO: salary=[3200,3500,2800,3100,3300,3000,50000] -> print mean, median, mean excluding values>=10000
salary=np.array([3200,3500,2800,3100,3300,3000,50000])
print(np.mean(salary))
print(np.median(salary))
print(np.mean(salary[salary < 10000]))

print("\n--- 8-3: std()/var() ---")
# TODO: A and B daily-visitor arrays -> print each one's mean, std, and CV (std/mean*100)
daily_visitor_A = np.array([1000, 1200, 1100, 1300, 1150, 1250, 1350, 1200, 1100, 1250])
daily_visitor_B = np.array([2000, 2200, 2100, 2300, 2150, 2250, 2350, 2200, 2100, 2250])
print(np.mean(daily_visitor_A))
print(np.std(daily_visitor_A))
print(np.std(daily_visitor_A) / np.mean(daily_visitor_A) * 100)
print(np.mean(daily_visitor_B))
print(np.std(daily_visitor_B))
print(np.std(daily_visitor_B) / np.mean(daily_visitor_B) * 100)

print("\n--- 8-4: min/max/argmin/argmax ---")
# TODO: products + sales arrays -> print best (argmax) and worst (argmin) product name+value
products = np.array(["Product A", "Product B", "Product C", "Product D", "Product E"])
sales = np.array([1200, 2500, 1800, 3100, 2200])
print(products[np.argmax(sales)])
print(products[np.argmin(sales)])

print("\n--- 8-5: cumsum()/cumprod() ---")
# TODO: quarterly_new=[800,1200,950,1400], target=5000 -> print cumulative total + achievement% per quarter
quarterly_new = np.array([800, 1200, 950, 1400])
target = 5000
cumulative_total = np.cumsum(quarterly_new)
print(cumulative_total)
print(cumulative_total / target * 100)

print("\n--- 8-6: percentile()/quantile() ---")
# TODO: 100 random sales + 2 injected outliers -> compute IQR, print outliers outside 1.5*IQR range
sales = np.concatenate([
    np.random.normal(150000, 30000, 90),
    np.random.normal(1500000, 300000, 10)
])
sales = np.abs(sales).astype(int)
print(np.percentile(sales, 25))
print(np.percentile(sales, 75))

print("\n✅ Fill in each ________ above with real code, then re-run to see all 6 results.")
print("✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 6개 결과를 모두 볼 수 있습니다.")

--- 8-1: sum() ---
[1549 1544 1467 1314 1917]
[1638 1793 1356 1023 1256  725]
7791

--- 8-2: mean()/median() ---
9842.857142857143
3200.0
3150.0

--- 8-3: std()/var() ---
1190.0
99.498743710662
8.361238967282521
2190.0
99.498743710662
4.5433216306238355

--- 8-4: min/max/argmin/argmax ---
Product D
Product A

--- 8-5: cumsum()/cumprod() ---
[ 800 2000 2950 4350]
[16. 40. 59. 87.]

--- 8-6: percentile()/quantile() ---
130576.75
177217.5

✅ Fill in each ________ above with real code, then re-run to see all 6 results.
✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 6개 결과를 모두 볼 수 있습니다.


---
# ⚠️ Common Mistakes

**Mistake 1 — Confusing `axis=0` with `axis=1`.**
This is the single most common mistake in this whole section. `axis=0` collapses ROWS (one result per column); `axis=1` collapses COLUMNS (one result per row).  
이번 섹션에서 가장 흔한 실수입니다. `axis=0`은 행을 축소(열마다 결과 하나)하고, `axis=1`은 열을 축소(행마다 결과 하나)합니다.  
✅ **Fix:** Use the memory aid — the axis NUMBER is the dimension that DISAPPEARS from the result shape. `(4,3)` with `axis=0` → `(3,)`; with `axis=1` → `(4,)`.  
✅ **해결법:** 니모닉을 사용하세요 — axis 숫자는 결과 shape에서 사라지는 차원입니다. `(4,3)`에 `axis=0`이면 `(3,)`, `axis=1`이면 `(4,)`가 됩니다.

**Mistake 2 — Judging an entire distribution from the mean alone.**
If average income is reported as 5,000,000 but the median is 2,000,000, most people actually earn well below the average — the mean alone hides that.  
평균 소득이 500만원으로 보고되어도 중앙값이 200만원이라면, 실제로 대다수는 평균보다 훨씬 적게 법니다 — 평균만 봐서는 이걸 알 수 없습니다.  
✅ **Fix:** Report mean AND median together whenever outliers are possible, not just one.  
✅ **해결법:** 이상치 가능성이 있다면 평균 하나만이 아니라 항상 평균과 중앙값을 함께 보고하세요.

**Mistake 3 — Calling `np.mean()` on an empty array.**
`np.mean(np.array([]))` doesn't raise a clean error — it returns `nan` along with a runtime warning, which can silently propagate into later calculations.  
`np.mean(np.array([]))`은 명확한 에러 대신 런타임 경고와 함께 `nan`을 반환하며, 이후 계산으로 조용히 전파될 수 있습니다.  
✅ **Fix:** Check `.size > 0` before aggregating, especially after a filtering step that might return zero rows.  
✅ **해결법:** 특히 필터링 이후 0개 행이 남을 수 있는 경우, 집계 전에 `.size > 0`을 먼저 확인하세요.

**Mistake 4 — Mixing up `ddof=0` and `ddof=1`.**
`ddof=0` (the default) computes the POPULATION formula; `ddof=1` computes the SAMPLE formula (what most statistics textbooks default to when estimating a population from a sample).  
`ddof=0`(기본값)은 모집단 공식을, `ddof=1`은 표본 공식(대부분의 통계 교과서가 표본으로 모집단을 추정할 때 기본으로 쓰는 방식)을 계산합니다.  
✅ **Fix:** If your data IS the entire population, use `ddof=0`. If it's a sample representing a larger population, use `ddof=1`.  
✅ **해결법:** 데이터가 모집단 전체라면 `ddof=0`을, 더 큰 모집단을 대표하는 표본이라면 `ddof=1`을 사용하세요.

**Mistake 5 — Forgetting `argmin()`/`argmax()` flatten a 2D array without `axis`.**
`np.argmin(matrix)` returns a single flattened-index position, not a `(row, col)` pair — the same flattening trap applies to `cumsum()`/`cumprod()` producing an unintended 1D result when `axis` is omitted on a 2D array.  
`np.argmin(matrix)`는 `(행, 열)` 쌍이 아니라 flatten된 단일 인덱스를 반환합니다 — `axis`를 생략한 2D 배열에서 `cumsum()`/`cumprod()`가 의도치 않은 1D 결과를 내는 것도 같은 flatten 함정입니다.    
✅ **Fix:** Always specify `axis` explicitly on 2D+ arrays unless you specifically want the flattened result.  
✅ **해결법:** flatten된 결과를 원하는 게 아니라면, 2D 이상의 배열에서는 항상 `axis`를 명시적으로 지정하세요.

**Mistake 6 — Confusing the VALUE (`min`/`max`) with the POSITION (`argmin`/`argmax`).**
`np.max(arr)` tells you WHAT the largest value is; `np.argmax(arr)` tells you WHERE it is (its index) — mixing them up gives a value where you wanted an index, or vice versa.  
`np.max(arr)`는 가장 큰 값이 '무엇'인지 알려주고, `np.argmax(arr)`는 그 값이 '어디'에 있는지 (인덱스) 알려줍니다 — 둘을 혼동하면 인덱스가 필요한 곳에 값이, 값이 필요한 곳에 인덱스가 들어갑니다.  
✅ **Fix:** Read `arg` as "the argument (index) that produces this" — `argmax` = "the index where the max is."  
✅ **해결법:** `arg`를 "이 값을 만드는 인자(인덱스)"로 읽으세요 — `argmax` = "최댓값이 있는 인덱스".

**Mistake 7 — Expecting `cumsum()`/`cumprod()` to return a single number.**
Unlike `sum()`, `cumsum()` returns an array the SAME size as the input — one running total per position, not one final total.  
`sum()`과 달리 `cumsum()`은 입력과 같은 크기의 배열을 반환합니다 — 최종 합계 하나가 아니라, 각 위치까지의 누적값입니다.  
✅ **Fix:** If you only want the final total, use `.sum()`; use `cumsum()` specifically when you need every intermediate running total (like a YTD tracker).  
✅ **해결법:** 최종 합계만 필요하면 `.sum()`을 쓰고, 모든 중간 누적값(YTD 트래커 등)이 필요할 때만 `cumsum()`을 사용하세요.

**Mistake 8 — Mixing up `percentile`'s 0–100 scale with `quantile`'s 0.0–1.0 scale.**
`np.percentile(data, 0.75)` doesn't mean "75th percentile" — it means the 0.75th percentile, which is nearly the minimum value. The two functions are equivalent, just on different scales.  
`np.percentile(data, 0.75)`는 "75번째 백분위"가 아니라 "0.75번째 백분위"를 의미하며, 이는 거의 최솟값에 가깝습니다. 두 함수는 동일하지만 스케일만 다릅니다.  
✅ **Fix:** `percentile` takes 0–100 (`np.percentile(data, 75)`); `quantile` takes 0.0–1.0 (`np.quantile(data, 0.75)`). Don't cross the scales.  
✅ **해결법:** `percentile`은 0~100(`np.percentile(data, 75)`), `quantile`은 0.0~1.0(`np.quantile(data, 0.75)`)입니다 — 스케일을 섞지 마세요.

---
# 💡 Tips
Useful tips or shortcuts

- Say the axis mnemonic out loud until it's automatic: "the axis number is the dimension that disappears."   
  axis 니모닉을 자동이 될 때까지 소리 내어 말해보세요: "axis 숫자는 사라지는 차원이다."
- When outliers are a possibility, always compute BOTH mean and median — the gap between them tells you as much as either number alone.  
  이상치 가능성이 있다면 항상 평균과 중앙값을 둘 다 계산하세요 — 둘의 차이 자체가 각 숫자 하나만큼이나 많은 정보를 줍니다.
- The 5-number summary (`np.percentile(data, [0, 25, 50, 75, 100])`) is worth memorizing as a single line — it's the fastest way to describe an unfamiliar dataset.   
  5-number summary(`np.percentile(data, [0, 25, 50, 75, 100])`)는 한 줄로 외워둘 가치가 있습니다 — 낯선 데이터셋을 가장 빠르게 파악하는 방법입니다.

---
# 🔗 Related Concepts

```
Section 7 — Vectorization & Broadcasting
   (loop-free operations, automatic shape matching)
        ↓
🔵 Section 8 — Aggregation   ← you are here
   (sum, mean/median, std/var, min/max, cumsum, percentile)
        ↓
Section 9 — Random / Sorting / Filtering
        ↓
Section 10 — Pandas + NumPy integration
        ↓
Sections 11-12 — Business KPIs, missing values
        ↓
Pandas → SQL → Tableau
```

*How is today's topic connected to other concepts?*

Section 7's Broadcasting patterns (`data - col_min`, `actual / targets`) almost always take their SMALL array from an aggregation — `col_min = data.min(axis=0)` is Section 8 feeding directly into Section 7. Going forward, Section 11's entire premise (business KPIs like growth rate, retention rate, LTV) is built from exactly these six aggregation functions, just with business-specific names.

섹션 7의 Broadcasting 패턴(`data - col_min`, `actual / targets`)은 거의 항상 작은 배열을 집계에서 가져옵니다 — `col_min = data.min(axis=0)`은 섹션 8이 섹션 7로 바로 이어지는 지점입니다. 앞으로 섹션 11의 모든 전제(성장률, 리텐션율, LTV 같은 비즈니스 KPI)는 정확히 이 6가지 집계 함수로 만들어지며, 다만 비즈니스 용어로 이름이 붙을 뿐입니다.

---
# 💼 Business Example
*How would a Business Analyst use this?*

**Scenario / 시나리오:**
You're building a monthly KPI dashboard. You need to (1) compute each region's YTD cumulative sales, (2) find the best and worst performing region, (3) compute the median purchase (since the data has outliers), and (4) classify customers into percentile-based tiers.  
월간 KPI 대시보드를 구축하는 상황입니다. 필요한 것: (1) 각 지역의 YTD 누적 매출 계산, (2) 최고·최저 실적 지역 찾기, (3) 이상치가 있는 데이터이므로 중앙값 계산, (4) 백분위 기준 고객 등급 분류.

**To-do / 할 일:**
- [x] Compute YTD cumulative sales per region.  
      지역별 YTD 누적 매출을 계산합니다.
- [x] Find the best/worst region by annual total.  
      연간 합계 기준 최고·최저 지역을 찾습니다.
- [x] Compute median purchase to avoid outlier distortion.  
      이상치 왜곡을 피하기 위해 중앙값 구매금액을 계산합니다.
- [x] Classify customers into percentile-based tiers.  
      백분위 기준으로 고객 등급을 분류합니다.

In [10]:
import numpy as np

# 1. YTD cumulative sales per region
region_monthly = np.array([
    [1200, 1350, 1100, 1400, 1600, 1500],
    [800, 850, 780, 900, 950, 920],
    [600, 620, 590, 650, 680, 660]
])
regions = ["Seoul", "Busan", "Daegu"]
ytd = np.cumsum(region_monthly, axis=1)
print("YTD by region (through the last month):")
for r, y in zip(regions, ytd[:, -1]):
    print(f"  {r}: {y:,}")

# 2. Best/worst region by annual total
annual = np.sum(region_monthly, axis=1)
print(f"\nBest: {regions[np.argmax(annual)]}, Worst: {regions[np.argmin(annual)]}")

# 3. Median purchase (outlier-heavy data)
np.random.seed(2)
purchases = np.concatenate([
    np.random.normal(150000, 30000, 90),
    np.random.normal(1500000, 300000, 10)
])
purchases = np.abs(purchases).astype(int)
print(f"\nMean: {purchases.mean():,.0f}, Median: {np.median(purchases):,.0f}")

# 4. Percentile-based customer tiers
p50, p90 = np.percentile(purchases, [50, 90])
print(f"\nMedian cutoff: {p50:,.0f}, Top 10% cutoff: {p90:,.0f}")

YTD by region (through the last month):
  Seoul: 8,150
  Busan: 5,200
  Daegu: 3,800

Best: Seoul, Worst: Daegu

Mean: 284,196, Median: 149,713

Median cutoff: 149,713, Top 10% cutoff: 276,581


---
# 📝 Summary
*Write today's concept in 3~5 sentences.*

Aggregation functions collapse an array's many values into fewer: `np.sum()` totals, `mean()`/`median()` find a typical value (with median resisting outliers), `std()`/`var()` measure spread, `min()`/`max()`/`argmin()`/`argmax()` find extremes and their positions, `cumsum()`/`cumprod()` build running totals, and `percentile()`/`quantile()` find rank-based cutoffs. The single most important detail across all six is the `axis` parameter — `axis=0` collapses rows (per-column result), `axis=1` collapses columns (per-row result), and the axis number is literally the dimension that disappears from the output shape.

집계 함수는 배열의 여러 값을 더 적은 값으로 축소합니다: `np.sum()`은 합계, `mean()`/`median()`은 대표값(중앙값은 이상치에 강함), `std()`/`var()`는 퍼짐 정도, `min()`/`max()`/`argmin()`/`argmax()`는 극값과 그 위치, `cumsum()`/`cumprod()`는 누적값, `percentile()`/`quantile()`은 순위 기준값을 구합니다. 이 6가지 모두에서 가장 중요한 디테일은 `axis` 파라미터입니다 — `axis=0`은 행을 축소(열별 결과), `axis=1`은 열을 축소(행별 결과)하며, axis 숫자는 말 그대로 결과 shape에서 사라지는 차원입니다.

---
# 📌 One Sentence Summary
Today's topic in ONE sentence.

> Aggregation functions (sum, mean/median, std/var, min/max, cumsum, percentile) summarize many values into few, and the `axis` parameter — where the axis number is the dimension that disappears — controls which direction gets collapsed.

> 집계 함수(sum, mean/median, std/var, min/max, cumsum, percentile)는 여러 값을 적은 값으로 요약하며, `axis` 파라미터(축 번호가 곧 사라지는 차원)가 어느 방향이 축소되는지를 결정합니다.

---
# ❓ Review Questions

**Q1.** For a `(4, 3)` array, what shape does `np.sum(arr, axis=0)` return, and what does `np.sum(arr, axis=1)` return?  
`(4, 3)` 배열에서 `np.sum(arr, axis=0)`은 어떤 shape을 반환하며, `np.sum(arr, axis=1)`은 어떤 shape을 반환하나요?

axis=0 sums down the rows, so it returns one value for each column: shape (3,). axis=1 sums across the columns, so it returns one value for each row: shape (4,).  
axis=0은 행 방향으로 내려가면서 계산해서 각 column의 합을 하나씩 남깁니다. 따라서 (3,)이 됩니다. axis=1은 열 방향으로 가로질러 계산해서 각 row의 합을 하나씩 남기므로 (4,)가 됩니다.

**Q2.** Why is the median often a better summary than the mean for revenue or salary data?  
매출이나 연봉 데이터에서 평균보다 중앙값이 더 나은 대표값인 경우가 많은 이유는 무엇인가요?

The mean is strongly affected by extreme values, while the median is much more resistant to outliers.  
평균은 극단적으로 큰 값(outlier)의 영향을 많이 받지만, 중앙값은 그런 값의 영향을 상대적으로 적게 받습니다.

**Q3.** What's the difference between `ddof=0` and `ddof=1` in `np.std()`?  
`np.std()`에서 `ddof=0`과 `ddof=1`은 어떻게 다른가요?

ddof=0 calculates population standard deviation, while ddof=1 calculates sample standard deviation using n-1 in the denominator.  
ddof=0은 전체 모집단의 표준편차를 계산할 때 사용하고, ddof=1은 표본의 표준편차를 추정할 때 사용합니다.

**Q4.** What's the difference between `np.max()` and `np.argmax()`?  
`np.max()`와 `np.argmax()`는 어떻게 다른가요?

np.max() returns the maximum value, while np.argmax() returns the index where the maximum value occurs.  
np.max()는 최댓값 자체를 반환하고, np.argmax()는 최댓값의 위치(인덱스)를 반환합니다.

**Q5.** What does `np.percentile(data, 75)` mean, and how is it different from `np.percentile(data, 0.75)`?  
`np.percentile(data, 75)`는 무엇을 의미하며, `np.percentile(data, 0.75)`와는 어떻게 다른가요?

np.percentile(data, 75) returns the value below which 75% of the data falls. np.percentile(data, 0.75) means the 0.75th percentile, not 75%.  
np.percentile(data, 75)는 데이터의 75%가 그 값 이하에 위치하는 지점을 의미합니다.

---
*📅 Try answering these again in a few days.*