# 📚 Section 9: Random / Sorting / Filtering
> Random, Sorting & Filtering — Generating reproducible test data, ranking values, finding unique categories, capping outliers, and catching NaN/Inf

---
# 🎯 Learning Objective
Today I want to learn:
- [x] How `np.random.seed()` makes random data reproducible, and the 4 core random-generation functions (`rand`, `randn`, `randint`, `choice`)
- [x] How to sort and rank an array (`np.sort()` vs `arr.sort()`, `np.argsort()` for Top-N patterns), and count unique categories (`np.unique()`)
- [x] How to cap values into a valid range with `np.clip()`, and detect missing/infinite values with `np.isnan()`/`np.isinf()`/`np.isfinite()`

---
# 🧠 Concept

## What is it?
*(Explain it in your own words.)*

This section is a toolkit of six practical utilities that don't fit neatly into "creation" or "aggregation": generating reproducible random test data, ranking and sorting real data, counting unique categories, capping outlier values into a safe range, and catching missing (`NaN`) or infinite (`Inf`) values before they corrupt downstream calculations.

이번 섹션은 "생성"이나 "집계"로 딱 떨어지지 않는 6가지 실용적인 도구 모음입니다: 재현 가능한 랜덤 테스트 데이터 생성, 실제 데이터의 순위·정렬, 고유 카테고리 개수 파악, 이상치를 안전한 범위로 제한, 이후 계산을 오염시키기 전에 결측치(`NaN`)나 무한값(`Inf`)을 잡아내는 것입니다.

### Six practical utilities / 6가지 실용 도구

| Function / 함수 | Purpose / 목적 |
|---|---|
| `np.random.seed()` | Reproducible randomness (재현 가능한 난수) |
| `rand`/`randn`/`randint`/`choice` | Generate random data (랜덤 데이터 생성) |
| `np.sort()` / `np.argsort()` | Order values, get rank (정렬, 순위) |
| `np.unique()` | Find distinct values + frequency (고유값과 빈도) |
| `np.clip()` | Cap values to a range (값 범위 제한) |
| `np.isnan()` / `np.isinf()` | Detect missing/infinite values (결측치·무한값 탐지) |

## Why do we use it?
*(When is it useful?)*

Because before you can analyze real data, you often need to simulate test data to prototype with, rank it to find winners and losers, understand what categories exist, tame extreme values, and confirm the data is actually clean — these six tools cover that entire "getting data analysis-ready" phase.

실제 데이터를 분석하기 전, 종종 프로토타입을 위한 테스트 데이터를 시뮬레이션하고, 순위를 매겨 우수/저조 항목을 찾고, 어떤 카테고리가 있는지 파악하고, 극단값을 다스리고, 데이터가 실제로 깨끗한지 확인해야 합니다 — 이 6가지 도구가 "분석 가능한 상태로 만드는" 전체 과정을 다룹니다.

## When is it used in Business Analytics?
*(Real-world use case)*

- Simulating realistic test data (purchase amounts, ages, A/B groups) before real data is available.  
  실제 데이터가 준비되기 전, 현실적인 테스트 데이터(구매금액, 나이, A/B 그룹)를 시뮬레이션할 때.  
- Auto-generating a performance leaderboard (Top-N sales reps, products, regions).  
  성과 리더보드(상위 N명의 영업사원, 상품, 지역)를 자동 생성할 때.  
- Counting how many customers fall into each category/channel/grade.  
  각 카테고리·채널·등급에 몇 명의 고객이 속하는지 셀 때.  
- Winsorizing extreme values, and running a data-quality check for `NaN`/`Inf` right after loading a file.  
  극단값을 Winsorizing하거나, 파일을 불러온 직후 `NaN`/`Inf` 데이터 품질 검사를 할 때.

---
# 📝 Syntax

## Basic Syntax

In [1]:
import numpy as np

np.random.seed(42)                       # reproducibility
sample = np.random.randint(1, 100, 5)    # random data
print(sample)

sorted_vals = np.sort(sample)             # ascending order
print(sorted_vals, np.argsort(sample))

vals, counts = np.unique(sample, return_counts=True)   # unique + frequency
print(vals, counts)

print(np.clip(sample, 20, 80))            # cap into [20, 80]
print(np.isnan(sample.astype(float)))     # NaN check

[52 93 15 72 61]
[15 52 61 72 93] [2 0 4 3 1]
[15 52 61 72 93] [1 1 1 1 1]
[52 80 20 72 61]
[False False False False False]


## Common Variations

In [2]:
import numpy as np
np.random.seed(0)

# rand vs randn vs randint vs choice
print(np.random.rand(3))              # 0-1 uniform
print(np.random.randn(3))             # standard normal
print(np.random.randint(1, 10, 3))    # integers, high excluded
print(np.random.choice(["A", "B", "C"], size=3, p=[0.6, 0.3, 0.1]))

# descending sort/rank via [::-1]
scores = np.array([70, 95, 60, 88])
print(np.sort(scores)[::-1])
print(np.argsort(scores)[::-1])

# clip with only one side bounded
print(np.clip(np.array([-5, 3, 12]), 0, None))

# isfinite catches both NaN and Inf at once
data = np.array([1.0, np.nan, np.inf, 4.0])
print(data[np.isfinite(data)])

[0.5488135  0.71518937 0.60276338]
[-2.2683282   1.33354538 -0.84272405]
[7 9 9]
['A' 'A' 'B']
[95 88 70 60]
[1 3 0 2]
[ 0  3 12]
[1. 4.]


---
# 🧪 Small Examples

## Example 1: `np.random.seed()` — Reproducible Team-Shared Results
### 9-1. np.random.seed() — 재현성 확보

In [3]:
import numpy as np

# Without a seed -- different every run
print("No seed:")
print(np.random.randint(1, 100, 5))
print(np.random.randint(1, 100, 5))   # different values

# With a fixed seed -- always the same
print("\nseed=42:")
np.random.seed(42)
print(np.random.randint(1, 100, 5))

np.random.seed(42)   # reset the seed
print(np.random.randint(1, 100, 5))   # identical to the line above

# Modern recommended approach: an explicit Generator (NumPy 1.17+)
rng = np.random.default_rng(seed=42)
print("\ndefault_rng:")
print(rng.integers(1, 100, 5))

No seed:
[47 89 82 38 26]
[78 73 10 21 81]

seed=42:
[52 93 15 72 61]
[52 93 15 72 61]

default_rng:
[ 9 77 65 44 43]


## Example 2: The 4 Random-Generation Functions — Simulating Customer Behavior
### 9-2. 난수 생성 4종 — rand / randn / randint / choice

| Function / 함수 | Range / 범위 | Distribution / 분포 | Typical use / 주요 용도 |
|---|---|---|---|
| `np.random.rand(shape)` | 0.0 ~ 1.0 | Uniform (균등) | Probabilities, ratios (확률, 비율) |
| `np.random.randn(shape)` | Unbounded (제한 없음) | Standard normal (표준정규) | Standardized features, Z-score |
| `np.random.randint(low, high, size)` | low ~ high-1 | Discrete uniform (이산 균등) | Integer counts, IDs |
| `np.random.choice(arr, size, replace)` | elements of `arr` | Selection (선택) | Sampling, bootstrapping |

In [4]:
import numpy as np
np.random.seed(42)

# Business: simulate 1000 customers for behavior analysis
n = 1000

# purchase amount via a log-normal-ish simulation (exp of a normal)
log_purchase = np.random.randn(n) * 0.8 + 11.5
purchase = np.exp(log_purchase).astype(int)

# visit count -- integers 1 to 20
visits = np.random.randint(1, 21, size=n)

# A/B test group assignment (50:50)
group = np.random.choice(["Control", "Treatment"], size=n, p=[0.5, 0.5])

print(f"Purchase — mean: {purchase.mean():,.0f}, median: {np.median(purchase):,.0f}")
print(f"Visits — mean: {visits.mean():.1f}")
print(f"Control: {np.sum(group == 'Control')}, Treatment: {np.sum(group == 'Treatment')}")

Purchase — mean: 137,683, median: 100,734
Visits — mean: 10.5
Control: 498, Treatment: 502


## Example 3: `argsort()` — Auto-Ranking 10 Sales Reps
### 9-3. np.sort() / np.argsort() — 정렬과 순위

In [5]:
import numpy as np

# Business: rank 10 sales reps by revenue, descending
np.random.seed(1)
reps = [f"Rep{i+1:02d}" for i in range(10)]
revenue = np.random.randint(3000, 15000, size=10)

rank_idx = np.argsort(revenue)[::-1]   # descending-order indices

print(f"{'Rank':>4} {'Rep':>8} {'Revenue':>10}")
for rank, idx in enumerate(rank_idx):
    print(f"{rank+1:>4} {reps[idx]:>8} {revenue[idx]:>10,}")

top3 = revenue[rank_idx[:3]]
bottom3 = revenue[rank_idx[-3:]]
print(f"\nTop 3 average: {top3.mean():,.0f}")
print(f"Bottom 3 average: {bottom3.mean():,.0f}")
print(f"Gap: {top3.mean() - bottom3.mean():,.0f}")

Rank      Rep    Revenue
   1    Rep04     13,955
   2    Rep05     10,813
   3    Rep10     10,751
   4    Rep02      8,192
   5    Rep07      8,056
   6    Rep09      7,225
   7    Rep06      5,895
   8    Rep03      3,905
   9    Rep01      3,235
  10    Rep08      3,144

Top 3 average: 11,840
Bottom 3 average: 3,428
Gap: 8,412


## Example 4: `np.unique()` — Channel Distribution (Pandas `value_counts()`'s Cousin)
### 9-4. np.unique() — 고유값과 빈도

In [6]:
import numpy as np

# Business: which acquisition channel brings in the most customers?
np.random.seed(42)
channels = np.random.choice(
    ["Search", "SNS", "Email", "Direct", "Referral"],
    size=1000,
    p=[0.35, 0.25, 0.20, 0.12, 0.08]
)

vals, counts = np.unique(channels, return_counts=True)

# sort by frequency, descending
sort_idx = np.argsort(counts)[::-1]
total = len(channels)

print(f"{'Channel':>10} {'Count':>7} {'Share':>8}")
for idx in sort_idx:
    print(f"{vals[idx]:>10} {counts[idx]:>7} {counts[idx]/total*100:>7.1f}%")

   Channel   Count    Share
    Search     365    36.5%
       SNS     248    24.8%
     Email     188    18.8%
    Direct     120    12.0%
  Referral      79     7.9%


## Example 5: `np.clip()` — Winsorizing Extreme Revenue Values
### 9-5. np.clip() — 값 범위 제한

In [7]:
import numpy as np

# Business: Winsorizing — replace the top/bottom 5% with the boundary value
np.random.seed(5)
revenue = np.random.exponential(100000, 1000).astype(int)

p5 = np.percentile(revenue, 5)
p95 = np.percentile(revenue, 95)
winsorized = np.clip(revenue, p5, p95)

print(f"Original — mean: {revenue.mean():,.0f}, std: {revenue.std():,.0f}")
print(f"Winsorized — mean: {winsorized.mean():,.0f}, std: {winsorized.std():,.0f}")
print(f"\nClip range: {p5:,.0f} ~ {p95:,.0f}")
print(f"Values clipped at top: {np.sum(revenue > p95)}")
print(f"Values clipped at bottom: {np.sum(revenue < p5)}")

Original — mean: 96,929, std: 93,917
Winsorized — mean: 92,827, std: 80,325

Clip range: 5,199 ~ 287,447
Values clipped at top: 50
Values clipped at bottom: 50


## Example 6: `isnan()` / `isinf()` — A 12-Month Data-Quality Check
### 9-6. np.isnan() / np.isinf() — 결측치·무한값 탐지

In [8]:
import numpy as np

# Business: check and auto-clean 12 months of data
monthly = np.array([
    1200, np.nan, 1100, 1400, 1600, np.nan,
    1300, np.inf, 1450, 1700, -1800, 2000
])

print("=== Data quality check ===")
print(f"Total values: {monthly.size}")
print(f"NaN count: {np.sum(np.isnan(monthly))}")
print(f"Inf count: {np.sum(np.isinf(monthly))}")
print(f"Negative count: {np.sum(monthly < 0)}")
print(f"Valid count: {np.sum(np.isfinite(monthly) & (monthly >= 0))}")

# Auto-clean: NaN/Inf -> mean of valid values, negatives -> 0
cleaned = monthly.copy()
valid_mask = np.isfinite(monthly) & (monthly >= 0)
valid_mean = monthly[valid_mask].mean()

cleaned[~np.isfinite(cleaned)] = valid_mean
cleaned[cleaned < 0] = 0

print(f"\nMean after cleaning: {cleaned.mean():,.0f}")
print("Cleaned data:", cleaned)

=== Data quality check ===
Total values: 12
NaN count: 2
Inf count: 1
Negative count: 1
Valid count: 8

Mean after cleaning: 1,346
Cleaned data: [1200.   1468.75 1100.   1400.   1600.   1468.75 1300.   1468.75 1450.
 1700.      0.   2000.  ]


## Example 7: Practice — One Mini-Exercise per Subtopic
### 연습 문제 (Practice Problems, 9-2 ~ 9-6)

**Note / 참고:** the original material has no practice problem for 9-1 (`np.random.seed()` alone), so this covers 9-2 through 9-6.
원문에는 9-1(`np.random.seed()` 단독)에 대한 연습 문제가 없어, 9-2~9-6만 다룹니다.

1. **(9-2)** Simulate 500 customers: (a) purchase amount ~ Normal(mean=150000, std=50000), clipped to a minimum of 10000, (b) age ~ uniform integers 25-65, (c) channel: online 60% / offline 40%.  
   고객 500명을 시뮬레이션하세요: (a) 구매금액 ~ 정규분포(평균 150000, 표준편차 50000), 최소 10000으로 clip, (b) 나이 ~ 25-65 균등 정수, (c) 채널: 온라인 60% / 오프라인 40%.  
2. **(9-3)** 5 products' sales → rank them, print the top 3 names + sales.  
   5개 상품 판매량 → 순위를 매기고 상위 3개 이름+판매량을 출력하세요.  
3. **(9-4)** 50 customers' grade array → print each unique grade's count and percentage.  
   50명 고객 등급 배열 → 고유 등급별 인원 수와 비율을 출력하세요.  
4. **(9-5)** A conversion-rate array → clip values below 0 to 0 and above 1 to 1.  
   전환율 배열 → 0 미만은 0으로, 1 초과는 1로 clip하세요.  
5. **(9-6)** An array with NaN and Inf values → replace them with the median of the valid values.  
   NaN과 Inf가 섞인 배열 → 유효값의 중앙값으로 대체하세요.  

Fill in each `________` below, then run the cell.
아래 각 `________`를 채운 후 셀을 실행하세요.

In [12]:
# ✏️ Practice — replace each ________ line below, then run this cell.
# ✏️ 연습 문제 — 아래 각 ________ 줄을 채운 후 셀을 실행하세요.

import numpy as np

print("--- 9-2: random generation ---")
# TODO: np.random.seed(0); n=500; simulate purchase (Normal 150000/50000, clip min 10000),
# age (randint 25-66), channel (choice online 60%/offline 40%); print the 3 means/counts
np.random.seed(0)

n=500

purchase = np.random.normal(150000,50000,n)
purchase = np.clip(purchase,10000,None)

age = np.random.randint(25,66,n)

channel = np.random.choice(
    ["online","offline"],
    size=n,
    p=[0.6,0.4]
)

print(purchase.mean())
print(age.mean())
print(np.unique(channel, return_counts=True))

print("\n--- 9-3: sort()/argsort() ---")
# TODO: products + sales arrays -> argsort descending, print top 3 name+sales
products=np.array([
"A","B","C","D","E"
])
sales=np.array([
100,500,300,200,700
])

idx=np.argsort(sales)[::-1]
top3=idx[:3]
print(products[top3])
print(sales[top3])

print("\n--- 9-4: unique() ---")
# TODO: np.random.seed(0); grades=np.random.choice([...4 tiers...], size=50, p=[...])
# print each unique value's count and percentage
np.random.seed(0)

grades=np.random.choice(
["VIP","Gold","Silver","Bronze"],
size=50,
p=[0.1,0.2,0.4,0.3]
)
values, counts = np.unique(
    grades,
    return_counts=True
)
percentage = counts / len(grades) *100
for v,c,p in zip(values,counts,percentage):
    print(v,c,p)

print("\n--- 9-5: clip() ---")
# TODO: cvr = [-0.02,0.03,0.05,1.02,0.038,-0.01,0.041,1.5] -> clip to [0,1], print before/after
cvr=np.array([
-0.02,
0.03,
0.05,
1.02,
0.038,
-0.01,
0.041,
1.5
])


print(cvr)

clipped=np.clip(cvr,0,1)

print(clipped)

print("\n--- 9-6: isnan()/isinf() ---")
# TODO: data with nan/inf mixed in -> replace with the median of the finite values
data=np.array([
100,
200,
np.nan,
300,
np.inf,
400
])
finite_mask=np.isfinite(data)
finite_values=data[finite_mask]
median=np.median(finite_values)
data[~finite_mask]=median
print(data)

print("\n✅ Fill in each ________ above with real code, then re-run to see all 5 results.")
print("✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 5개 결과를 모두 볼 수 있습니다.")

--- 9-2: random generation ---
148732.2780333783
45.126
(array(['offline', 'online'], dtype='<U7'), array([205, 295]))

--- 9-3: sort()/argsort() ---
['E' 'B' 'C']
[700 500 300]

--- 9-4: unique() ---
Bronze 14 28.000000000000004
Gold 5 10.0
Silver 26 52.0
VIP 5 10.0

--- 9-5: clip() ---
[-0.02   0.03   0.05   1.02   0.038 -0.01   0.041  1.5  ]
[0.    0.03  0.05  1.    0.038 0.    0.041 1.   ]

--- 9-6: isnan()/isinf() ---
[100. 200. 250. 300. 250. 400.]

✅ Fill in each ________ above with real code, then re-run to see all 5 results.
✅ 위 각 ________ 를 실제 코드로 채운 뒤 다시 실행하면 5개 결과를 모두 볼 수 있습니다.


---
# ⚠️ Common Mistakes

**Mistake 1 — Skipping `np.random.seed()` when reproducibility matters.**
Without a fixed seed, every run of your simulation code produces different numbers — fine for real production randomness, but a problem when sharing analysis code with a team or writing a reproducible report.  
seed을 고정하지 않으면 시뮬레이션 코드를 실행할 때마다 다른 값이 나옵니다 — 실제 프로덕션의 무작위성에는 괜찮지만, 팀과 분석 코드를 공유하거나 재현 가능한 리포트를 작성할 때는 문제가 됩니다.  
✅ **Fix:** Call `np.random.seed(42)` (or any agreed-upon number — the value itself doesn't matter, team consistency does) at the top of any shareable simulation code.  
✅ **해결법:** 공유할 시뮬레이션 코드 맨 위에 `np.random.seed(42)`(숫자 자체는 의미 없고, 팀 내 통일이 중요)를 호출하세요.

**Mistake 2 — Passing a tuple to `np.random.rand()`.**
Unlike `np.zeros((3, 4))`, `np.random.rand()` takes shape as SEPARATE arguments — `np.random.rand(3, 4)` works, but `np.random.rand((3, 4))` raises a `TypeError`.  
`np.zeros((3, 4))`와 달리 `np.random.rand()`는 shape을 별도의 인자로 받습니다 — `np.random.rand(3, 4)`는 되지만 `np.random.rand((3, 4))`는 `TypeError`를 발생시킵니다.  
✅ **Fix:** Remember `rand`/`randn` want `shape_dim1, shape_dim2, ...` with no parentheses around them, unlike most other array-creation functions.  
✅ **해결법:** `rand`/`randn`은 다른 대부분의 배열 생성 함수와 달리 괄호로 감싸지 않은 `차원1, 차원2, ...` 형태를 받는다는 걸 기억하세요.

**Mistake 3 — Forgetting `randint(low, high)` excludes `high`.**
`np.random.randint(0, 10)` can return `0` through `9` — never `10` — the same exclusive-upper-bound convention as `range()` and `np.arange()`.  
`np.random.randint(0, 10)`은 `0`부터 `9`까지만 반환합니다 — `10`은 절대 나오지 않습니다 — `range()`, `np.arange()`와 같은 상한 미포함 관례입니다.  
✅ **Fix:** To include `10` as a possible value, write `randint(0, 11)`.  
✅ **해결법:** `10`도 나오게 하려면 `randint(0, 11)`로 작성하세요.

**Mistake 4 — Confusing `np.sort(arr)` with `arr.sort()`.**
`np.sort(arr)` returns a new sorted array and leaves `arr` untouched (Copy); `arr.sort()` sorts `arr` in place and returns `None` — mixing these up either loses your sorted result or unexpectedly reorders your original data.  
`np.sort(arr)`는 새로운 정렬된 배열을 반환하고 `arr`은 그대로 둡니다(Copy). `arr.sort()`는 `arr` 자체를 제자리에서 정렬하고 `None`을 반환합니다 — 혼동하면 정렬 결과를 잃거나 원본 데이터의 순서가 예상 밖으로 바뀝니다.  
✅ **Fix:** Use `np.sort(arr)` when you need to keep the original order too; use `arr.sort()` only when you're sure you want to permanently reorder `arr`.  
✅ **해결법:** 원본 순서도 유지해야 한다면 `np.sort(arr)`을, `arr`을 영구히 재정렬해도 된다는 확신이 있을 때만 `arr.sort()`를 사용하세요.

**Mistake 5 — Assuming `np.unique()` sorts by frequency.**
`np.unique()` always returns values sorted in ascending order BY VALUE, never by how often they occur — `return_counts=True` gives you the counts, but not in frequency order.  
`np.unique()`는 항상 값 기준 오름차순으로 정렬된 결과를 반환하며, 등장 빈도 순이 아닙니다 — `return_counts=True`로 빈도수는 얻을 수 있지만 빈도순 정렬은 아닙니다.  
✅ **Fix:** For frequency order, feed the counts into `np.argsort(counts)[::-1]` and index both arrays with the result.  
✅ **해결법:** 빈도순이 필요하면 `np.argsort(counts)[::-1]`를 사용해서 두 배열 모두 그 인덱스로 재정렬하세요.

**Mistake 6 — Expecting `np.clip()` to modify the array in place.**
`np.clip(arr, 0, 10)` returns a NEW array — `arr` itself is unchanged unless you reassign the result back to it.  
`np.clip(arr, 0, 10)`은 새로운 배열을 반환합니다 — 결과를 다시 대입하지 않으면 `arr` 자체는 바뀌지 않습니다.  
✅ **Fix:** Write `arr = np.clip(arr, 0, 10)` if you want the change to stick.  
✅ **해결법:** 변경을 유지하려면 `arr = np.clip(arr, 0, 10)`처럼 재할당하세요.

**Mistake 7 — Testing for NaN with `arr == np.nan`.**
This ALWAYS returns `False`, even where a value actually is NaN — by definition, `NaN` is not equal to anything, including itself.  
이 방식은 실제로 값이 NaN이어도 항상 `False`를 반환합니다 — 정의상 `NaN`은 자기 자신을 포함해 그 무엇과도 같지 않습니다.  
✅ **Fix:** Always use `np.isnan(arr)` to detect NaN — never `==`.  
✅ **해결법:** NaN을 확인할 때는 항상 `np.isnan(arr)`을 사용하세요 — `==`는 절대 안 됩니다.

**Mistake 8 — Not checking `np.isfinite()` after risky operations.**
Operations like `np.log(0)` (`-inf`) or `0 / 0` (`nan`) don't raise an error — they silently produce a non-finite value that can poison a later `sum()` or `mean()`.  
`np.log(0)`(`-inf`)나 `0 / 0`(`nan`) 같은 연산은 에러를 내지 않고, 이후 `sum()`이나 `mean()`을 오염시킬 수 있는 비유한(non-finite) 값을 조용히 만들어냅니다.  
✅ **Fix:** After any operation that could divide by zero or take a log of zero, check `np.isfinite()` before trusting the result.  
✅ **해결법:** 0으로 나누거나 0의 로그를 취할 가능성이 있는 연산 후에는, 결과를 신뢰하기 전에 `np.isfinite()`로 확인하세요.

---
# 💡 Tips
Useful tips or shortcuts

- `μ + σ * np.random.randn(n)` is the standard formula for simulating any custom normal distribution, not just the standard one.
  `μ + σ * np.random.randn(n)`은 표준정규분포가 아닌 원하는 평균·표준편차의 정규분포를 시뮬레이션하는 표준 공식입니다.
- `argsort(arr)[::-1][:n]` (descending Top-N) is worth having memorized cold — it appears constantly across ranking, leaderboards, and Top-N filtering.
  `argsort(arr)[::-1][:n]`(내림차순 Top-N)은 확실히 외워둘 가치가 있는 패턴입니다 — 순위, 리더보드, Top-N 필터링 어디서나 계속 등장합니다.
- `np.isfinite(arr) & (arr >= 0)` is the standard "give me only the valid, non-negative values" mask — a good default whenever cleaning business metrics.
  `np.isfinite(arr) & (arr >= 0)`는 "유효하고 음수가 아닌 값만" 마스크의 표준 패턴입니다 — 비즈니스 지표를 정제할 때 좋은 기본값입니다.

---
# 🔗 Related Concepts

```
Section 8 — Aggregation
   (sum, mean/median, std/var, min/max, cumsum, percentile)
        ↓
🔵 Section 9 — Random / Sorting / Filtering   ← you are here
   (seed, rand/randn/randint/choice, sort/argsort, unique, clip, isnan/isinf)
        ↓
Section 10 — Pandas + NumPy integration
   (np.unique -> df.value_counts(), np.sort -> df.sort_values())
        ↓
Sections 11-12 — Business KPIs, missing values
        ↓
Pandas → SQL → Tableau
```

*How is today's topic connected to other concepts?*

This section closes the loop with Section 8's aggregation: `argsort()` is what turns a plain aggregation into a RANKING, and `np.unique(..., return_counts=True)` is essentially a manual `groupby().count()`. Every function here has a near-identical Pandas equivalent you'll meet directly in Section 10 — `np.unique()` becomes `.value_counts()`, `np.sort()` becomes `.sort_values()`, and `np.isnan()` becomes `.isna()`.

이번 섹션은 섹션 8의 집계와 이어집니다: `argsort()`는 단순 집계를 순위로 바꿔주는 도구이고, `np.unique(..., return_counts=True)`는 사실상 수동으로 만든 `groupby().count()`입니다. 여기 나온 거의 모든 함수는 섹션 10에서 바로 만나게 될 Pandas의 대응 함수가 있습니다 — `np.unique()`는 `.value_counts()`가, `np.sort()`는 `.sort_values()`가, `np.isnan()`은 `.isna()`가 됩니다.

---
# 💼 Business Example
*How would a Business Analyst use this?*

**Scenario / 시나리오:**
You're prototyping an A/B test analysis pipeline before real data arrives. You need to (1) simulate 300 reproducible test users, (2) rank them by revenue to spot top performers, (3) count how many fall into each test group, and (4) clean any simulated data-quality issues (negative values, `NaN`).
실제 데이터가 도착하기 전 A/B 테스트 분석 파이프라인을 프로토타입으로 만드는 상황입니다. 필요한 것: (1) 재현 가능한 테스트 유저 300명 시뮬레이션, (2) 상위 실적자를 찾기 위한 매출 기준 순위 매기기, (3) 각 테스트 그룹에 몇 명이 속하는지 계산, (4) 시뮬레이션 중 발생한 데이터 품질 문제(음수, `NaN`) 정제.

**To-do / 할 일:**
- [ ] Simulate reproducible test data with a fixed seed.
      고정된 seed로 재현 가능한 테스트 데이터를 시뮬레이션합니다.
- [ ] Rank users by revenue and find the top 5.
      매출 기준으로 유저 순위를 매기고 상위 5명을 찾습니다.
- [ ] Count users per test group with `np.unique()`.
      `np.unique()`로 테스트 그룹별 유저 수를 셉니다.
- [ ] Clean any negative or missing simulated values.
      시뮬레이션에서 발생한 음수·결측 값을 정제합니다.

In [10]:
import numpy as np

np.random.seed(7)
n = 300

# 1. Simulate test data (with an intentional data-quality wrinkle)
revenue = 50000 + 20000 * np.random.randn(n)
revenue[5] = np.nan   # simulate a missing value
group = np.random.choice(["A", "B"], size=n, p=[0.5, 0.5])

# 2. Rank by revenue (push NaN to the bottom for ranking purposes)
safe_revenue = np.where(np.isnan(revenue), -np.inf, revenue)
top5_idx = np.argsort(safe_revenue)[::-1][:5]
print("Top 5 revenue:", np.round(revenue[top5_idx], 0))

# 3. Count per group
vals, counts = np.unique(group, return_counts=True)
for v, c in zip(vals, counts):
    print(f"Group {v}: {c}")

# 4. Clean negative/missing values
clean_revenue = np.clip(revenue, 0, None)
valid_mean = revenue[np.isfinite(revenue)].mean()
clean_revenue[np.isnan(clean_revenue)] = valid_mean
print(f"\nClean revenue mean: {clean_revenue.mean():,.0f}")

Top 5 revenue: [95199. 94952. 91276. 90581. 88240.]
Group A: 161
Group B: 139

Clean revenue mean: 49,582


---
# 📝 Summary
*Write today's concept in 3~5 sentences.*

This section's six tools prepare data for realistic analysis: `np.random.seed()` (plus `rand`/`randn`/`randint`/`choice`) generates reproducible test data across 4 distributions, `np.sort()`/`argsort()` order values and — combined with Fancy Indexing — build Top-N rankings, `np.unique()` counts distinct categories (a manual `value_counts()`), `np.clip()` caps outliers into a safe range without deleting them (Winsorizing), and `np.isnan()`/`np.isinf()`/`np.isfinite()` catch missing or infinite values before they silently corrupt a mean or sum. Nearly every function here has a close Pandas equivalent, making this section a preview of Section 10.

이번 섹션의 6가지 도구는 실제 분석을 위한 데이터를 준비합니다: `np.random.seed()`(그리고 `rand`/`randn`/`randint`/`choice`)는 4가지 분포로 재현 가능한 테스트 데이터를 생성하고, `np.sort()`/`argsort()`는 값을 정렬하며 Fancy Indexing과 결합해 Top-N 순위를 만들고, `np.unique()`는 고유 카테고리 개수를 세며(수동 `value_counts()`), `np.clip()`은 이상치를 삭제하지 않고 안전한 범위로 제한하고(Winsorizing), `np.isnan()`/`np.isinf()`/`np.isfinite()`는 평균이나 합계를 조용히 오염시키기 전에 결측·무한값을 잡아냅니다. 여기 거의 모든 함수는 Pandas의 대응 함수가 있어, 이번 섹션은 섹션 10의 예고편이기도 합니다.

---
# 📌 One Sentence Summary
Today's topic in ONE sentence.

> This section's toolkit — reproducible random generation, sort/rank, unique-value counting, value clipping, and NaN/Inf detection — gets raw or simulated data into a clean, analyzable shape, with a near-1:1 Pandas equivalent for almost every function.

> 이번 섹션의 도구 모음(재현 가능한 난수 생성, 정렬/순위, 고유값 카운트, 값 제한, NaN/Inf 탐지)은 원본·시뮬레이션 데이터를 분석 가능한 깨끗한 상태로 만들며, 거의 모든 함수가 Pandas에 1:1 대응 함수를 가지고 있습니다.

---
# ❓ Review Questions

**Q1.** Why does setting `np.random.seed(42)` before generating random numbers matter for team collaboration?
난수를 생성하기 전에 `np.random.seed(42)`를 설정하는 것이 팀 협업에서 왜 중요한가요?

**Q2.** Which of the 4 random functions (`rand`, `randn`, `randint`, `choice`) would you use to simulate customer ages, and which for a Z-score-style standardized feature?
고객 나이를 시뮬레이션하려면 4가지 랜덤 함수(`rand`, `randn`, `randint`, `choice`) 중 무엇을 쓰고, Z-score 스타일의 표준화된 특성에는 무엇을 쓰나요?

**Q3.** What's the difference between `np.sort(arr)` and `arr.sort()`?
`np.sort(arr)`와 `arr.sort()`는 어떻게 다른가요?

**Q4.** What does `np.clip(data, 0, None)` do, and why is `None` used instead of a number?
`np.clip(data, 0, None)`은 무엇을 하며, 숫자 대신 왜 `None`을 사용하나요?

**Q5.** Why does `arr == np.nan` always return `False`, and what should you use instead?
`arr == np.nan`은 왜 항상 `False`를 반환하며, 대신 무엇을 사용해야 하나요?

---
*📅 Try answering these again in a few days.*